export interface VocabularyItem {
  id: number;
  japanese: string;
  reading: string;
  meaning: string;
}

export interface Chapter {
  chapter: number;
  words: VocabularyItem[];
}

const chapter1Words: VocabularyItem[] = [
  { id: 1, reading: 'わたし', japanese: '私', meaning: 'Saya' },
  { id: 2, reading: 'あなた', japanese: 'あなた', meaning: 'Kamu' },
  { id: 3, reading: 'あのひと', japanese: 'あの人', meaning: 'Orang itu (biasa)' },
  { id: 4, reading: 'あのかた', japanese: 'あの方', meaning: 'Orang itu (sopan)' },
  { id: 5, reading: '～さん', japanese: '～さん', meaning: 'Saudara…….' },
  { id: 6, reading: '～ちゃん', japanese: '～ちゃん', meaning: 'Panggilan untuk anak laki/perempuan' },
  { id: 7, reading: '～じん', japanese: '～人', meaning: 'Orang…….' },
  { id: 8, reading: 'せんせい', japanese: '先生', meaning: 'Guru,dosen' },
  { id: 9, reading: 'きょうし', japanese: '教師', meaning: 'Guru,dosen (dipakai untuk kalangan sendiri)' },
  { id: 10, reading: 'がくせい', japanese: '学生', meaning: 'Siswa,murid' },
  { id: 11, reading: 'かいしゃいん', japanese: '会社員', meaning: 'Pegawai perusahaan' },
  { id: 12, reading: 'しゃいん', japanese: '社員', meaning: 'Pegawai perusahaan' },
  { id: 13, reading: 'ぎんこういん', japanese: '銀行員', meaning: 'Pegawai bank' },
  { id: 14, reading: 'いしゃ', japanese: '医者', meaning: 'Dokter' },
  { id: 15, reading: 'けんきゅうしゃ', japanese: '研究者', meaning: 'Peneliti' },
  { id: 16, reading: 'だいがく', japanese: '大学', meaning: 'Universitas' },
  { id: 17, reading: 'びょういん', japanese: '病院', meaning: 'Rumah sakit' },
  { id: 18, reading: 'だれ', japanese: 'だれ', meaning: 'Siapa (biasa)' },
  { id: 19, reading: 'どなた', japanese: 'どなた', meaning: 'Siapa (sopan)' },
  { id: 20, reading: '～さい', japanese: '～歳', meaning: 'Umur…..' },
  { id: 21, reading: 'なんさい', japanese: '何歳', meaning: 'Umur berapa?(biasa)' },
  { id: 22, reading: 'おいくつ', japanese: 'おいくつ', meaning: 'Umur berapa?(sopan)' },
  { id: 23, reading: 'はい', japanese: 'はい', meaning: 'Iya' },
  { id: 24, reading: 'いいえ', japanese: 'いいえ', meaning: 'Tidak' },
  { id: 25, reading: 'はじめまして', japanese: 'はじめまして', meaning: 'Perkenalkan' },
  { id: 26, reading: '～からきました', japanese: '～から来ました', meaning: 'Datang dari…..' },
  { id: 27, reading: 'どうぞよろしくおねがいします', japanese: 'どうぞよろしくお願します', meaning: 'Terimalah perkenalan saya' },
  { id: 28, reading: 'しつれいですが', japanese: '失礼ですが', meaning: 'Permisi' },
  { id: 29, reading: 'おなまえは', japanese: 'お名前は', meaning: 'Nama anda siapa?' },
  { id: 30, reading: 'アメリカ', japanese: 'アメリカ', meaning: 'Amerika' },
  { id: 31, reading: 'イギリス', japanese: 'イギリス', meaning: 'Inggris' },
  { id: 32, reading: 'インド', japanese: 'インド', meaning: 'India' },
  { id: 33, reading: 'インドネシア', japanese: 'インドネシア', meaning: 'Indonesia' },
  { id: 34, reading: 'かんこく', japanese: '韓国', meaning: 'Korea' },
  { id: 35, reading: 'ちゅうごく', japanese: '中国', meaning: 'China' },
  { id: 36, reading: 'ドイツ', japanese: 'ドイツ', meaning: 'Jerman' },
  { id: 37, reading: 'にほん', japanese: '日本', meaning: 'Jepang' },
  { id: 38, reading: 'フランス', japanese: 'フランス', meaning: 'Perancis' },
];

const chapter2Words: VocabularyItem[] = [
  { id: 39, reading: "これ", japanese: "これ", meaning: "Ini" },
  { id: 40, reading: "それ", japanese: "それ", meaning: "Itu (dekat)" },
  { id: 41, reading: "あれ", japanese: "あれ", meaning: "Itu (jauh)" },
  { id: 42, reading: "この～", japanese: "この～", meaning: "～ini" },
  { id: 43, reading: "その～", japanese: "その～", meaning: "～itu (dekat)" },
  { id: 44, reading: "あの～", japanese: "あの～", meaning: "～itu (jauh)" },
  { id: 45, reading: "ほん", japanese: "本", meaning: "Buku" },
  { id: 46, reading: "じしょ", japanese: "辞書", meaning: "Kamus" },
  { id: 47, reading: "ざっし", japanese: "雑誌", meaning: "Majalah" },
  { id: 48, reading: "しんぶん", japanese: "新聞", meaning: "Koran" },
  { id: 49, reading: "ノート", japanese: "ノート", meaning: "Buku catatan" },
  { id: 50, reading: "てちょう", japanese: "手帳", meaning: "Buku agenda" },
  { id: 51, reading: "めいし", japanese: "名刺", meaning: "Kartu nama" },
  { id: 52, reading: "カード", japanese: "カード", meaning: "Kartu" },
  { id: 53, reading: "えんぴつ", japanese: "鉛筆", meaning: "Pensil" },
  { id: 54, reading: "ボールペン", japanese: "ボールペン", meaning: "Bolpoin" },
  { id: 55, reading: "シャープペンシル", japanese: "シャープペンシル", meaning: "Pensil mekanik" },
  { id: 56, reading: "かぎ", japanese: "鍵", meaning: "Kunci" },
  { id: 57, reading: "とけい", japanese: "時計", meaning: "Jam , arloji" },
  { id: 58, reading: "かさ", japanese: "傘", meaning: "Payung" },
  { id: 59, reading: "かばん", japanese: "鞄", meaning: "Tas" },
  { id: 60, reading: "テレビ", japanese: "テレビ", meaning: "Televisi" },
  { id: 61, reading: "ラジオ", japanese: "ラジオ", meaning: "Radio" },
  { id: 62, reading: "カメラ", japanese: "カメラ", meaning: "Kamera" },
  { id: 63, reading: "コンピューター", japanese: "コンピューター", meaning: "Komputer" },
  { id: 64, reading: "くるま", japanese: "車", meaning: "Mobil" },
  { id: 65, reading: "つくえ", japanese: "机", meaning: "Meja" },
  { id: 66, reading: "いす", japanese: "椅子", meaning: "Kursi" },
  { id: 67, reading: "チョコレート", japanese: "チョコレート", meaning: "Coklat" },
  { id: 68, reading: "コーヒー", japanese: "コーヒー", meaning: "Kopi" },
  { id: 69, reading: "おみやげ", japanese: "お土産", meaning: "Oleh-oleh" },
  { id: 70, reading: "えいご", japanese: "英語", meaning: "Bahasa inggris" },
  { id: 71, reading: "にほんご", japanese: "日本語", meaning: "Bahasa jepang" },
  { id: 72, reading: "～ご", japanese: "～語", meaning: "Bahasa ～" },
  { id: 73, reading: "なん", japanese: "何", meaning: "Apa" },
  { id: 74, reading: "そう", japanese: "そう", meaning: "Begitu" },
  { id: 75, reading: "あのう", japanese: "あのう", meaning: "Eee ...(ungkapan ketika ragu)" },
  { id: 76, reading: "えっ", japanese: "えっ", meaning: "Eh (diucapkan ketika mendengar sesuatu diluar dugaan)" },
  { id: 77, reading: "どうぞ", japanese: "どうぞ", meaning: "Silakan" },
  { id: 78, reading: "どうもありがとうございます", japanese: "どうもありがとうございます", meaning: "Terima kasih" },
  { id: 79, reading: "そうですか", japanese: "そうですか", meaning: "O,begitu, benarkah?" },
  { id: 80, reading: "ちがいます", japanese: "違います", meaning: "Bukan , Tidak , Salah" },
  { id: 81, reading: "あ", japanese: "あ", meaning: "O,eh (dipakai ketika sadar)" },
  { id: 82, reading: "これからおせわになります", japanese: "これからお世話になります", meaning: "Mulai sekarang saya akan meminta bantuannya" },
  { id: 83, reading: "こちらこそよろしくおねがいします", japanese: "こちらこそよろしくおねがいします", meaning: "Ya sama-sama" },
];

const chapter3Words: VocabularyItem[] = [
  { id: 84, reading: 'ここ', japanese: 'ここ', meaning: 'Disini' },
  { id: 85, reading: 'そこ', japanese: 'そこ', meaning: 'Disitu' },
  { id: 86, reading: 'あそこ', japanese: 'あそこ', meaning: 'Disana' },
  { id: 87, reading: 'どこ', japanese: 'どこ', meaning: 'Dimana?' },
  { id: 88, reading: 'こちら', japanese: 'こちら', meaning: 'Disini' },
  { id: 89, reading: 'そちら', japanese: 'そちら', meaning: 'Disitu' },
  { id: 90, reading: 'あちら', japanese: 'あちら', meaning: 'Disana' },
  { id: 91, reading: 'どちら', japanese: 'どちら', meaning: 'Dimana ?' },
  { id: 92, reading: 'きょうしつ', japanese: '教室', meaning: 'Ruang kelas' },
  { id: 93, reading: 'しょくどう', japanese: '食堂', meaning: 'Ruang makan, Kantin' },
  { id: 94, reading: 'じむしょ', japanese: '事務所', meaning: 'Kantor' },
  { id: 95, reading: 'かいぎしつ', japanese: '会議室', meaning: 'Ruang rapat' },
  { id: 96, reading: 'うけつけ', japanese: '受付', meaning: 'Meja informasi' },
  { id: 97, reading: 'ロビー', japanese: 'ロビー', meaning: 'Ruang tunggu, lobi' },
  { id: 98, reading: 'へや', japanese: '部屋', meaning: 'Kamar' },
  { id: 99, reading: 'おてあらい', japanese: 'お手洗い', meaning: 'Kamar kecil, WC' },
  { id: 100, reading: 'トイレ', japanese: 'トイレ', meaning: 'Toilet' },
  { id: 101, reading: 'かいだん', japanese: '階段', meaning: 'Tangga' },
  { id: 102, reading: 'エレベーター', japanese: 'エレベーター', meaning: 'Lift' },
  { id: 103, reading: 'エスカレーター', japanese: 'エスカレーター', meaning: 'Eskalator, tangga berjalan' },
  { id: 104, reading: 'じどうはんばいき', japanese: '自動販売機', meaning: 'Mesin jual otomatis' },
  { id: 105, reading: 'でんわ', japanese: '電話', meaning: 'Telepon' },
  { id: 106, reading: 'おくに', japanese: 'お国', meaning: 'Negara' },
  { id: 107, reading: 'かいしゃ', japanese: '会社', meaning: 'Perusahaan' },
  { id: 108, reading: 'うち', japanese: '家', meaning: 'Rumah' },
  { id: 109, reading: 'くつ', japanese: '靴', meaning: 'Sepatu' },
  { id: 110, reading: 'ネクタイ', japanese: 'ネクタイ', meaning: 'Dasi' },
  { id: 111, reading: 'ワイン', japanese: 'ワイン', meaning: 'Anggur putih' },
  { id: 112, reading: 'うりば', japanese: '売り場', meaning: 'Tempat penjualan' },
  { id: 113, reading: 'ちか', japanese: '地下', meaning: 'Bawah tanah , basement' },
  { id: 114, reading: '～かい', japanese: '～階', meaning: 'lantai～/ tingkat～' },
  { id: 115, reading: 'なんがい', japanese: '何階', meaning: 'Lantai berapa?' },
  { id: 116, reading: '～えん', japanese: '～円', meaning: '～yen' },
  { id: 117, reading: 'いくら', japanese: 'いくら', meaning: 'Berapa?' },
  { id: 118, reading: 'ひゃく', japanese: '百', meaning: 'Seratus' },
  { id: 119, reading: 'せん', japanese: '千', meaning: 'Seribu' },
  { id: 120, reading: 'まん', japanese: '万', meaning: 'Puluh ribu' },
  { id: 121, reading: 'すみません', japanese: 'すみません', meaning: 'Maaf' },
  { id: 122, reading: 'どうも', japanese: 'どうも', meaning: 'Terima kasih' },
  { id: 123, reading: 'いらっしゃいませ', japanese: 'いらっしゃいませ', meaning: 'Selamat datang' },
  { id: 124, reading: 'みせてください', japanese: '見せてください', meaning: 'Tolong perlihatkan' },
  { id: 125, reading: 'じゃ', japanese: 'じゃ', meaning: 'Kalau begitu' },
  { id: 126, reading: '～をください', japanese: '～をください', meaning: 'Tolong ～' },
  { id: 127, reading: 'イタリア', japanese: 'イタリア', meaning: 'Italia' },
  { id: 128, reading: 'スイス', japanese: 'スイス', meaning: 'Swis' },
  { id: 129, reading: 'フランス', japanese: 'フランス', meaning: 'Perancis' },
  { id: 130, reading: 'ジャカルタ', japanese: 'ジャカルタ', meaning: 'Jakarta' },
  { id: 131, reading: 'バンコク', japanese: 'バンコク', meaning: 'Bangkok' },
  { id: 132, reading: 'ベルリン', japanese: 'ベルリン', meaning: 'Berlin' },
  { id: 133, reading: 'おくじょう', japanese: '屋上', meaning: 'Lantai atas' },
  { id: 134, reading: 'レストラン', japanese: 'レストラン', meaning: 'Restoran' },
  { id: 135, reading: 'ゆうえんち', japanese: '遊園地', meaning: 'Tempat hiburan' },
  { id: 136, reading: 'もよおしものかいじょう', japanese: '催し物会場', meaning: 'Tempat pertunjukan' },
  { id: 137, reading: 'めがね', japanese: '眼鏡', meaning: 'Kacamata' },
  { id: 138, reading: 'スポーツようひん', japanese: 'スポーツ用品', meaning: 'Peralatan olahraga' },
  { id: 139, reading: 'りょこうようひん', japanese: '旅行用品', meaning: 'Peralatan wisata' },
  { id: 140, reading: 'こどものふく', japanese: '子供の服', meaning: 'Pakaian anak' },
  { id: 141, reading: 'おもちゃ', japanese: 'おもちゃ', meaning: 'Mainan' },
  { id: 142, reading: 'ぶんぼうぐ', japanese: '文房具', meaning: 'Alat tulis' },
  { id: 143, reading: 'かぐ', japanese: '家具', meaning: 'Perlengkapan rumah' },
  { id: 144, reading: 'しょっき', japanese: '食器', meaning: 'Peralatan makan' },
  { id: 145, reading: 'でんかせいひん', japanese: '電化製品', meaning: 'Barang elektronik' },
  { id: 146, reading: 'しんしふく', japanese: '紳士服', meaning: 'Pakaian pria' },
  { id: 147, reading: 'ふじんふく', japanese: '婦人服', meaning: 'Pakaian wanita' },
  { id: 148, reading: 'アクセサリー', japanese: 'アクセサリー', meaning: 'Perhiasan, aksesoris' },
  { id: 149, reading: 'けしょうひん', japanese: '化粧品', meaning: 'Kosmetik' },
  { id: 150, reading: 'しょくひん', japanese: '食品', meaning: 'Makanan' },
];

const chapter4Words: VocabularyItem[] = [
  { id: 151, reading: 'おきます', japanese: '起きます', meaning: 'Bangun tidur' },
  { id: 152, reading: 'ねます', japanese: '寝ます', meaning: 'Tidur' },
  { id: 153, reading: 'はたらきます', japanese: '働きます', meaning: 'Bekerja' },
  { id: 154, reading: 'やすみます', japanese: '休みます', meaning: 'Beristirahat , libur' },
  { id: 155, reading: 'べんきょうします', japanese: '勉強します', meaning: 'Belajar' },
  { id: 156, reading: 'おわります', japanese: '終わります', meaning: 'Selesai' },
  { id: 157, reading: 'デパート', japanese: 'デパート', meaning: 'Departemen store' },
  { id: 158, reading: 'ぎんこう', japanese: '銀行', meaning: 'Bank' },
  { id: 159, reading: 'ゆうびんきょく', japanese: '郵便局', meaning: 'Kantor pos' },
  { id: 160, reading: 'としょかん', japanese: '図書館', meaning: 'Perpustakaan' },
  { id: 161, reading: 'びじゅつかん', japanese: '美術館', meaning: 'Gedung kesenian' },
  { id: 162, reading: 'いま', japanese: '今', meaning: 'Sekarang' },
  { id: 163, reading: '～じ', japanese: '～時', meaning: 'Jam , pukul' },
  { id: 164, reading: '～ふん／ぶん', japanese: '～分', meaning: 'Menit' },
  { id: 165, reading: 'はん', japanese: '半', meaning: 'Setengah' },
  { id: 166, reading: 'なんじ', japanese: '何時', meaning: 'Jam berapa?' },
  { id: 167, reading: 'なんぷん', japanese: '何分', meaning: 'Berapa menit ?' },
  { id: 168, reading: 'ごぜん', japanese: '午前', meaning: 'AM (waktu sebelum jam 12 siang)' },
  { id: 169, reading: 'ごご', japanese: '午後', meaning: 'PM (waktu setelah jam 12 siang)' },
  { id: 170, reading: 'あさ', japanese: '朝', meaning: 'Pagi' },
  { id: 171, reading: 'ひる', japanese: '昼', meaning: 'Siang' },
  { id: 172, reading: 'ばん', japanese: '晩', meaning: 'Malam' },
  { id: 173, reading: 'よる', japanese: '夜', meaning: 'Malam' },
  { id: 174, reading: 'おととい', japanese: '一昨日', meaning: '2 hari yang lalu , kemarin lusa' },
  { id: 175, reading: 'きのう', japanese: '昨日', meaning: 'Kemarin' },
  { id: 176, reading: 'きょう', japanese: '今日', meaning: 'Hari ini' },
  { id: 177, reading: 'あした', japanese: '明日', meaning: 'Besok' },
  { id: 178, reading: 'あさって', japanese: '明後日', meaning: 'Besok lusa' },
  { id: 179, reading: 'けさ', japanese: '今朝', meaning: 'Tadi pagi' },
  { id: 180, reading: 'こんばん', japanese: '今晩', meaning: 'Malam ini' },
  { id: 181, reading: 'やすみ', japanese: '休み', meaning: 'Istirahat, cuti, libur' },
  { id: 182, reading: 'ひるやすみ', japanese: '昼休み', meaning: 'Istirahat siang' },
  { id: 183, reading: 'しけん', japanese: '試験', meaning: 'Ujian' },
  { id: 184, reading: 'かいぎ', japanese: '会議', meaning: 'Rapat' },
  { id: 185, reading: 'えいが', japanese: '映画', meaning: 'Film' },
  { id: 186, reading: 'まいあさ', japanese: '毎朝', meaning: 'Setiap pagi' },
  { id: 187, reading: 'まいばん', japanese: '毎晩', meaning: 'Setiap malam' },
  { id: 188, reading: 'まいにち', japanese: '毎日', meaning: 'Setiap hari' },
  { id: 189, reading: 'げつようび', japanese: '月曜日', meaning: 'Hari senin' },
  { id: 190, reading: 'かようび', japanese: '火曜日', meaning: 'Hari selasa' },
  { id: 191, reading: 'すいようび', japanese: '水曜日', meaning: 'Hari rabo' },
  { id: 192, reading: 'もくようび', japanese: '木曜日', meaning: 'Hari kamis' },
  { id: 193, reading: 'きんようび', japanese: '金曜日', meaning: 'Hari jumat' },
  { id: 194, reading: 'どようび', japanese: '土曜日', meaning: 'Hari sabtu' },
  { id: 195, reading: 'にちようび', japanese: '日曜日', meaning: 'Hari minggu' },
  { id: 196, reading: 'なんようび', japanese: '何曜日', meaning: 'Hari apa?' },
  { id: 197, reading: '～から', japanese: '～から', meaning: 'Dari' },
  { id: 198, reading: '～まで', japanese: '～まで', meaning: 'Sampai' },
  { id: 199, reading: '～と～', japanese: '～と～', meaning: 'Dan' },
  { id: 200, reading: 'たいへんですね', japanese: '大変ですね', meaning: 'Berat ya,' },
  { id: 201, reading: 'ばんごう', japanese: '番号', meaning: 'Nomer' },
  { id: 202, reading: 'なんばん', japanese: '何番', meaning: 'Nomer berapa?' },
  { id: 203, reading: 'ニューヨーク', japanese: 'ニューヨーク', meaning: 'New york' },
  { id: 204, reading: 'ペキン', japanese: 'ペキン', meaning: 'Beijing' },
  { id: 205, reading: 'ロサンゼルス', japanese: 'ロサンゼルス', meaning: 'Los angels' },
  { id: 206, reading: 'ロンドン', japanese: 'ロンドン', meaning: 'London' },
  { id: 207, reading: 'けいさつしょ', japanese: '警察署', meaning: 'Kantor polisi' },
  { id: 208, reading: 'しょうぼうしょ', japanese: '消防署', meaning: 'Pemadam kebakaran' },
  { id: 209, reading: 'じほう', japanese: '時報', meaning: 'Pemberitahuan waktu' },
  { id: 210, reading: 'てんきよほう', japanese: '天気予報', meaning: 'Ramalan cuaca' },
  { id: 211, reading: 'でんわばんごうあんない', japanese: '電話番号案内', meaning: 'Petunjuk nomor telepon' },
];

const chapter5Words: VocabularyItem[] = [
  { id: 212, reading: 'いきます', japanese: '行きます', meaning: 'Pergi' },
  { id: 213, reading: 'きます', japanese: '来ます', meaning: 'Datang' },
  { id: 214, reading: 'かえります', japanese: '帰ります', meaning: 'Pulang' },
  { id: 215, reading: 'がっこう', japanese: '学校', meaning: 'Sekolahan' },
  { id: 216, reading: 'スーパー', japanese: 'スーパー', meaning: 'Supermarket' },
  { id: 217, reading: 'えき', japanese: '駅', meaning: 'Stasiun' },
  { id: 218, reading: 'ひこうき', japanese: '飛行機', meaning: 'Pesawat terbang' },
  { id: 219, reading: 'ふね', japanese: '船', meaning: 'Kapal laut' },
  { id: 220, reading: 'でんしゃ', japanese: '電車', meaning: 'Kereta listrik' },
  { id: 221, reading: 'ちかてつ', japanese: '地下鉄', meaning: 'Kereta bawah tanah' },
  { id: 222, reading: 'しんかんせん', japanese: '新幹線', meaning: 'Shinkansen' },
  { id: 223, reading: 'バス', japanese: 'バス', meaning: 'Bus' },
  { id: 224, reading: 'タクシー', japanese: 'タクシー', meaning: 'Taksi' },
  { id: 225, reading: 'じてんしゃ', japanese: '自転車', meaning: 'Sepeda' },
  { id: 226, reading: 'あるいて', japanese: '歩いて', meaning: 'Jalan kaki' },
  { id: 227, reading: 'ひと', japanese: '人', meaning: 'Orang' },
  { id: 228, reading: 'ともだち', japanese: '友達', meaning: 'Teman' },
  { id: 229, reading: 'かれ', japanese: '彼', meaning: 'Dia (laki-laki)' },
  { id: 230, reading: 'かのじょ', japanese: '彼女', meaning: 'Dia (perempuan)' },
  { id: 231, reading: 'かぞく', japanese: '家族', meaning: 'Keluarga' },
  { id: 232, reading: 'ひとりで', japanese: '一人で', meaning: 'Sendirian' },
  { id: 233, reading: 'せんしゅう', japanese: '先週', meaning: 'Minggu lalu' },
  { id: 234, reading: 'こんしゅう', japanese: '今週', meaning: 'Minggu ini' },
  { id: 235, reading: 'らいしゅう', japanese: '来週', meaning: 'Minggu depan' },
  { id: 236, reading: 'せんげつ', japanese: '先月', meaning: 'Bulan lalu' },
  { id: 237, reading: 'こんげつ', japanese: '今月', meaning: 'Bulan ini' },
  { id: 238, reading: 'らいげつ', japanese: '来月', meaning: 'Bulan depan' },
  { id: 239, reading: 'きょねん', japanese: '去年', meaning: 'Tahun lalu' },
  { id: 240, reading: 'ことし', japanese: '今年', meaning: 'Tahun ini' },
  { id: 241, reading: 'らいねん', japanese: '来年', meaning: 'Tahun depan' },
  { id: 242, reading: '～ねん', japanese: '～年', meaning: 'Tahun' },
  { id: 243, reading: 'なんねん', japanese: '何年', meaning: 'Tahun berapa?' },
  { id: 244, reading: '～がつ', japanese: '～月', meaning: 'Bulan' },
  { id: 245, reading: 'なんがつ', japanese: '何月', meaning: 'Bulan apa?' },
  { id: 246, reading: 'ついたち', japanese: '一日', meaning: 'Tanggal 1' },
  { id: 247, reading: 'ふつか', japanese: '二日', meaning: 'Tanggal 2 , 2 hari' },
  { id: 248, reading: 'みっか', japanese: '三日', meaning: 'Tanggal 3 , 3 hari' },
  { id: 249, reading: 'よっか', japanese: '四日', meaning: 'Tanggal 4 , 4 hari' },
  { id: 250, reading: 'いつか', japanese: '五日', meaning: 'Tanggal 5 , 5 hari' },
  { id: 251, reading: 'むいか', japanese: '六日', meaning: 'Tanggal 6 , 6 hari' },
  { id: 252, reading: 'なのか', japanese: '七日', meaning: 'Tanggal 7 , 7 hari' },
  { id: 253, reading: 'ようか', japanese: '八日', meaning: 'Tanggal 8, 8 hari' },
  { id: 254, reading: 'ここのか', japanese: '九日', meaning: 'Tanggal 9 , 9 hari' },
  { id: 255, reading: 'とおか', japanese: '十日', meaning: 'Tanggal 10, 10 hari' },
  { id: 256, reading: 'じゅうよっか', japanese: '十四日', meaning: 'Tanggal 14 , 14 hari' },
  { id: 257, reading: 'はつか', japanese: '二十日', meaning: 'Tanggal 20 , 20 hari' },
  { id: 258, reading: 'にじゅうよっか', japanese: '二十四日', meaning: 'Tanggal 24 , 24 hari' },
  { id: 259, reading: '～にち', japanese: '～日', meaning: 'Tanggal , hari' },
  { id: 260, reading: 'なんにち', japanese: '何日', meaning: 'Tanggal berapa, berapa hari' },
  { id: 261, reading: 'いつ', japanese: 'いつ', meaning: 'Kapan' },
  { id: 262, reading: 'たんじょうび', japanese: '誕生日', meaning: 'Hari ulang tahun' },
  { id: 263, reading: 'そうですね', japanese: 'そうですね', meaning: 'Ya begitulah' },
  { id: 264, reading: 'どういたしまして', japanese: 'どういたしまして', meaning: 'Sama-sama' },
  { id: 265, reading: '～ばんせん', japanese: '～番線', meaning: 'Peron nomor , jalur nomor' },
  { id: 266, reading: 'つぎの', japanese: '次の', meaning: 'Yang berikutnya' },
  { id: 267, reading: 'ふつう', japanese: '普通', meaning: 'Biasa' },
  { id: 268, reading: 'きゅうこう', japanese: '急行', meaning: 'Ekspres' },
  { id: 269, reading: 'とっきゅう', japanese: '特急', meaning: 'Super ekspres' },
  { id: 270, reading: 'しゅくさいじつ', japanese: '祝祭日', meaning: 'Hari libur nasional' },
  { id: 271, reading: 'がんじつ', japanese: '元日', meaning: 'Tahun baru' },
  { id: 272, reading: 'せいじんのひ', japanese: '成人の日', meaning: 'Hari perayaan menjadi dewasa' },
  { id: 273, reading: 'けんこくきねんのひ', japanese: '建国記念の日', meaning: 'Hari pembangunan nasional' },
  { id: 274, reading: 'しゅんぶんのひ', japanese: '春分の日', meaning: 'Hari equinox pada musim semi' },
  { id: 275, reading: 'しょうわのひ', japanese: '昭和の日', meaning: 'Hari showa' },
  { id: 276, reading: 'けんぽうきねんび', japanese: '憲法記念日', meaning: 'Hari peringatan konstitusi' },
  { id: 277, reading: 'みどりのひ', japanese: 'みどりのひ', meaning: 'Hari penghijauan' },
  { id: 278, reading: 'こどものひ', japanese: 'こどものひ', meaning: 'Hari anak' },
  { id: 279, reading: 'うみのひ', japanese: '海の日', meaning: 'Hari bahari' },
  { id: 280, reading: 'やまのひ', japanese: '山の日', meaning: 'Hari gunung' },
  { id: 281, reading: 'けいろうのひ', japanese: '敬老の日', meaning: 'Hari hormat kepada orang tua' },
  { id: 282, reading: 'しゅうぶんのひ', japanese: '秋分の日', meaning: 'Hari equinox pada musim gugur' },
  { id: 283, reading: 'たいいくのひ', japanese: '体育の日', meaning: 'Hari kesehatan olahraga' },
  { id: 284, reading: 'ぶんかのひ', japanese: '文化の日', meaning: 'Hari kebudayaan' },
  { id: 285, reading: 'きんろうかんしゃのひ', japanese: '勤労感謝の日', meaning: 'Hari bersyukur untuk pekerjaan' },
  { id: 286, reading: 'てんのうたんじょうび', japanese: '天皇誕生日', meaning: 'Hari ulang tahun kaisar' },
];

const chapter6Words: VocabularyItem[] = [
  { id: 287, reading: 'たべます', japanese: '食べます', meaning: 'Makan' },
  { id: 288, reading: 'のみます', japanese: '飲みます', meaning: 'Minum' },
  { id: 289, reading: 'すいます', japanese: '吸います', meaning: 'Menghisap / merokok' },
  { id: 290, reading: 'みます', japanese: '見ます', meaning: 'Melihat / menonton' },
  { id: 291, reading: 'ききます', japanese: '聞きます', meaning: 'Mendengar' },
  { id: 292, reading: 'よみます', japanese: '読みます', meaning: 'Membaca' },
  { id: 293, reading: 'かきます', japanese: '書きます', meaning: 'Menulis / menggambar' },
  { id: 294, reading: 'かいます', japanese: '買います', meaning: 'Membeli' },
  { id: 295, reading: 'とります', japanese: '撮ります', meaning: 'Mengambi (foto) / memotret' },
  { id: 296, reading: 'します', japanese: 'します', meaning: 'Melakukan / mengerjakan / berbuat' },
  { id: 297, reading: 'あいます', japanese: '会います', meaning: 'Bertemu' },
  { id: 298, reading: 'ごはん', japanese: 'ご飯', meaning: 'Nasi' },
  { id: 299, reading: 'あさごはん', japanese: '朝ご飯', meaning: 'Makan pagi / sarapan' },
  { id: 300, reading: 'ひるごはん', japanese: '昼ご飯', meaning: 'Makan siang' },
  { id: 301, reading: 'ばんごはん', japanese: '晩ご飯', meaning: 'Makan malam' },
  { id: 302, reading: 'パン', japanese: 'パン', meaning: 'Roti' },
  { id: 303, reading: 'たまご', japanese: '卵', meaning: 'Telur' },
  { id: 304, reading: 'にく', japanese: '肉', meaning: 'Daging' },
  { id: 305, reading: 'さかな', japanese: '魚', meaning: 'Ikan' },
  { id: 306, reading: 'やさい', japanese: '野菜', meaning: 'Sayuran' },
  { id: 307, reading: 'くだもの', japanese: '果物', meaning: 'Buah-buahan' },
  { id: 308, reading: 'みず', japanese: '水', meaning: 'Air' },
  { id: 309, reading: 'おちゃ', japanese: 'お茶', meaning: 'Teh jepang / teh hijau' },
  { id: 310, reading: 'こうちゃ', japanese: '紅茶', meaning: 'Teh' },
  { id: 311, reading: 'ぎゅうにゅう', japanese: '牛乳', meaning: 'Susu' },
  { id: 312, reading: 'ジュース', japanese: 'ジュース', meaning: 'Jus' },
  { id: 313, reading: 'ビール', japanese: 'ビール', meaning: 'Bir' },
  { id: 314, reading: 'おさけ', japanese: 'お酒', meaning: 'Minuman keras' },
  { id: 315, reading: 'たばこ', japanese: 'たばこ', meaning: 'Rokok' },
  { id: 316, reading: 'てがみ', japanese: '手紙', meaning: 'Surat' },
  { id: 317, reading: 'レポート', japanese: 'レポート', meaning: 'Laporan' },
  { id: 318, reading: 'しゃしん', japanese: '写真', meaning: 'Foto' },
  { id: 319, reading: 'ビデオ', japanese: 'ビデオ', meaning: 'Kaset video' },
  { id: 320, reading: 'みせ', japanese: '店', meaning: 'Toko' },
  { id: 321, reading: 'にわ', japanese: '庭', meaning: 'Halaman' },
  { id: 322, reading: 'しゅくだい', japanese: '宿題', meaning: 'Pekerjaan rumah / PR' },
  { id: 323, reading: 'テニス', japanese: 'テニス', meaning: 'Tenis' },
  { id: 324, reading: 'サッカー', japanese: 'サッカー', meaning: 'Sepak bola' },
  { id: 325, reading: 'はなみ', japanese: '花見', meaning: 'Hanami (menikmati bunga sakura)' },
  { id: 326, reading: 'なに', japanese: '何', meaning: 'Apa' },
  { id: 327, reading: 'いっしょに', japanese: 'いっしょに', meaning: 'Bersama-sama' },
  { id: 328, reading: 'ちょっと', japanese: 'ちょっと', meaning: 'Sebentar / sedikit' },
  { id: 329, reading: 'いつも', japanese: 'いつも', meaning: 'Selalu' },
  { id: 330, reading: 'ときどき', japanese: '時々', meaning: 'Kadang-kadang' },
  { id: 331, reading: 'それから', japanese: 'それから', meaning: 'Setelah itu / kemudian' },
  { id: 332, reading: 'ええ', japanese: 'ええ', meaning: 'Ya' },
  { id: 333, reading: 'いいですね', japanese: 'いいですね', meaning: 'Bagus ya / baik ya' },
  { id: 334, reading: 'わかりました', japanese: '分かりました', meaning: 'Mengerti / baik' },
  { id: 335, reading: 'じゃ、また', japanese: 'じゃ、また', meaning: 'Ok, sampai jumpa besok' },
  { id: 336, reading: 'メキシコ', japanese: 'メキシコ', meaning: 'Meksiko' },
  { id: 337, reading: 'きゅうり', japanese: 'きゅうり', meaning: 'Timun' },
  { id: 338, reading: 'トマト', japanese: 'トマト', meaning: 'Tomat' },
  { id: 339, reading: 'なす', japanese: 'なす', meaning: 'Terong' },
  { id: 340, reading: 'まめ', japanese: 'まめ', meaning: 'Kacang-kacangan' },
  { id: 341, reading: 'キャベツ', japanese: 'キャベツ', meaning: 'Kol' },
  { id: 342, reading: 'ねぎ', japanese: 'ねぎ', meaning: 'Daun bawang' },
  { id: 343, reading: 'はくさい', japanese: 'はくさい', meaning: 'Sawi' },
  { id: 344, reading: 'ほうれんそう', japanese: 'ほうれんそう', meaning: 'Bayam' },
  { id: 345, reading: 'レタス', japanese: 'レタス', meaning: 'Letas' },
  { id: 346, reading: 'じゃがいも', japanese: 'じゃがいも', meaning: 'Kentang' },
  { id: 347, reading: 'だいこん', japanese: 'だいこん', meaning: 'Lobak' },
  { id: 348, reading: 'たまねぎ', japanese: 'たまねぎ', meaning: 'Bawang' },
  { id: 349, reading: 'にんじん', japanese: 'にんじん', meaning: 'Wortel' },
  { id: 350, reading: 'いちご', japanese: 'いちご', meaning: 'Stroberi' },
  { id: 351, reading: 'もも', japanese: 'もも', meaning: 'Buah peach' },
  { id: 352, reading: 'すいか', japanese: 'すいか', meaning: 'Semangka' },
  { id: 353, reading: 'ぶどう', japanese: 'ぶどう', meaning: 'Anggur' },
  { id: 354, reading: 'なし', japanese: 'なし', meaning: 'Pir' },
  { id: 355, reading: 'かき', japanese: 'かき', meaning: 'Kesemek' },
  { id: 356, reading: 'みかん', japanese: 'みかん', meaning: 'Jeruk' },
  { id: 357, reading: 'りんご', japanese: 'りんご', meaning: 'Apel' },
  { id: 358, reading: 'バナナ', japanese: 'バナナ', meaning: 'Pisang' },
  { id: 359, reading: 'ぎゅうにく', japanese: 'ぎゅうにく', meaning: 'Daging sapi' },
  { id: 360, reading: 'とりにく', japanese: 'とりにく', meaning: 'Daging ayam' },
  { id: 361, reading: 'ぶたにく', japanese: 'ぶたにく', meaning: 'Daging babi' },
  { id: 362, reading: 'ソーセージ', japanese: 'ソーセージ', meaning: 'Sosis' },
  { id: 363, reading: 'ハム', japanese: 'ハム', meaning: 'Ham' },
  { id: 364, reading: 'あじ', japanese: 'あじ', meaning: 'Ikan mackerel' },
  { id: 365, reading: 'いわし', japanese: 'いわし', meaning: 'Ikan sarden' },
  { id: 366, reading: 'さば', japanese: 'さば', meaning: 'Ikan kembung' },
  { id: 367, reading: 'さんま', japanese: 'さんま', meaning: 'Ikan sauri pasifik' },
  { id: 368, reading: 'さけ', japanese: 'さけ', meaning: 'Ikan salmon' },
  { id: 369, reading: 'まぐろ', japanese: 'まぐろ', meaning: 'Ikan tuna' },
  { id: 370, reading: 'たい', japanese: 'たい', meaning: 'Ikan kakap' },
  { id: 371, reading: 'たら', japanese: 'たら', meaning: 'Ikan gabus' },
  { id: 372, reading: 'えび', japanese: 'えび', meaning: 'Udang' },
  { id: 373, reading: 'かに', japanese: 'かに', meaning: 'Kepiting' },
  { id: 374, reading: 'いか', japanese: 'いか', meaning: 'Cumi-cumi' },
  { id: 375, reading: 'たこ', japanese: 'たこ', meaning: 'Gurita' },
  { id: 376, reading: 'こめ', japanese: 'こめ', meaning: 'Beras' },
];

const chapter7Words: VocabularyItem[] = [
  { id: 377, reading: 'きります', japanese: '切ります', meaning: 'Memotong / menggunting' },
  { id: 378, reading: 'おくります', japanese: '送ります', meaning: 'Mengirim' },
  { id: 379, reading: 'あげます', japanese: 'あげます', meaning: 'Memberikan' },
  { id: 380, reading: 'もらいます', japanese: 'もらいます', meaning: 'Menerima / mendapatkan' },
  { id: 381, reading: 'かします', japanese: '貸します', meaning: 'Meminjamkan / menyewakan' },
  { id: 382, reading: 'かります', japanese: '借ります', meaning: 'Meminjam / menyewa' },
  { id: 383, reading: 'おしえます', japanese: '教えます', meaning: 'Mengajar' },
  { id: 384, reading: 'ならいます', japanese: '習います', meaning: 'Belajar (kepada)' },
  { id: 385, reading: 'かけます', japanese: 'かけます', meaning: 'Menelpon' },
  { id: 386, reading: 'て', japanese: '手', meaning: 'Tangan' },
  { id: 387, reading: 'はし', japanese: 'はし', meaning: 'Sumpit' },
  { id: 388, reading: 'スプーン', japanese: 'スプーン', meaning: 'Sendok' },
  { id: 389, reading: 'ナイフ', japanese: 'ナイフ', meaning: 'Pisau' },
  { id: 390, reading: 'フォーク', japanese: 'フォーク', meaning: 'Garpu' },
  { id: 391, reading: 'はさみ', japanese: 'はさみ', meaning: 'Gunting' },
  { id: 392, reading: 'パソコン', japanese: 'パソコン', meaning: 'Laptop' },
  { id: 393, reading: 'ケータイ', japanese: 'ケータイ', meaning: 'HP' },
  { id: 394, reading: 'メール', japanese: 'メール', meaning: 'Email' },
  { id: 395, reading: 'ねんがじょう', japanese: '年賀状', meaning: 'Kartu tahun baru' },
  { id: 396, reading: 'パンチ', japanese: 'パンチ', meaning: 'Pelubang kertas' },
  { id: 397, reading: 'ホッチキス', japanese: 'ホッチキス', meaning: 'Stapler' },
  { id: 398, reading: 'セロテープ', japanese: 'セロテープ', meaning: 'Selotip' },
  { id: 399, reading: 'けしゴム', japanese: '消しゴム', meaning: 'Penghapus karet' },
  { id: 400, reading: 'かみ', japanese: '紙', meaning: 'Kertas' },
  { id: 401, reading: 'はな', japanese: '花', meaning: 'Bunga' },
  { id: 402, reading: 'シャツ', japanese: 'シャツ', meaning: 'Kemeja' },
  { id: 403, reading: 'プレゼント', japanese: 'プレゼント', meaning: 'Hadiah / kado' },
  { id: 404, reading: 'にもつ', japanese: '荷物', meaning: 'Barang' },
  { id: 405, reading: 'おかね', japanese: 'お金', meaning: 'Uang' },
  { id: 406, reading: 'きっぷ', japanese: '切符', meaning: 'Karcis' },
  { id: 407, reading: 'クリスマス', japanese: 'クリスマス', meaning: 'Natal' },
  { id: 408, reading: 'ちち', japanese: '父', meaning: 'Ayah' },
  { id: 409, reading: 'はは', japanese: '母', meaning: 'Ibu' },
  { id: 410, reading: 'おとうさん', japanese: 'お父さん', meaning: 'Ayah orang lain' },
  { id: 411, reading: 'おかあさん', japanese: 'お母さん', meaning: 'Ibu orang lain' },
  { id: 412, reading: 'もう', japanese: 'もう', meaning: 'Sudah' },
  { id: 413, reading: 'まだ', japanese: 'まだ', meaning: 'Belum' },
  { id: 414, reading: 'これから', japanese: 'これから', meaning: 'Mulai dari sekarang' },
  { id: 415, reading: 'すてきですね', japanese: 'すてきですね', meaning: 'Bagus ya / indah ya' },
  { id: 416, reading: 'いらっしゃい', japanese: 'いらっしゃい', meaning: 'Selamat datang' },
  { id: 417, reading: 'どうぞおあがりください', japanese: 'どうぞおあがりください', meaning: 'Silakan masuk' },
  { id: 418, reading: 'しつれいします', japanese: '失礼します', meaning: 'Permisi' },
  { id: 419, reading: '～いかがですか', japanese: '～いかがですか', meaning: 'Bagaimana ? (menawarkan sesuatu kepada orang)' },
  { id: 420, reading: 'いただきます', japanese: 'いただきます', meaning: 'Selamat makan' },
  { id: 421, reading: 'ごちそうさまでした', japanese: 'ごちそうさまでした', meaning: 'Terima kasih atas hidangannya' },
  { id: 422, reading: 'スペイン', japanese: 'スペイン', meaning: 'Spanyol' },
  { id: 423, reading: 'かぞく', japanese: '家族', meaning: 'Keluarga' },
  { id: 424, reading: 'そぼ', japanese: '祖母', meaning: 'Nenek' },
  { id: 425, reading: 'そふ', japanese: '祖父', meaning: 'Kakek' },
  { id: 426, reading: 'そふぼ', japanese: '祖父母', meaning: 'Kakek nenek' },
  { id: 427, reading: 'りょうしん', japanese: '両親', meaning: 'Orang tua' },
  { id: 428, reading: 'いもうと', japanese: '妹', meaning: 'Adik perempuan' },
  { id: 429, reading: 'おとうと', japanese: '弟', meaning: 'Adik laki-laki' },
  { id: 430, reading: 'あね', japanese: '姉', meaning: 'Kakak perempuan' },
  { id: 431, reading: 'あに', japanese: '兄', meaning: 'Kakak laki-laki' },
  { id: 432, reading: 'きょうだい', japanese: '兄弟', meaning: 'Saudara kandung' },
  { id: 433, reading: 'つま', japanese: '妻', meaning: 'Istri' },
  { id: 434, reading: 'おっと', japanese: '夫', meaning: 'Suami' },
  { id: 435, reading: 'ふうふ', japanese: '夫婦', meaning: 'Pasangan suami istri' },
  { id: 436, reading: 'むすめ', japanese: '娘', meaning: 'Anak perempuan' },
  { id: 437, reading: 'むすこ', japanese: '息子', meaning: 'Anak laki-laki' },
  { id: 438, reading: 'こども', japanese: '子供', meaning: 'Anak' },
  { id: 439, reading: 'おばあさん', japanese: 'おばあさん', meaning: 'Nenek (orang lain)' },
  { id: 440, reading: 'おじいさん', japanese: 'おじいさん', meaning: 'Kakek (orang lain)' },
  { id: 441, reading: 'ごりょうしん', japanese: 'ごりょうしん', meaning: 'Orang tua (orang lain)' },
  { id: 442, reading: 'いもうとさん', japanese: 'いもうとさん', meaning: 'Adik perempuan (orang lain)' },
  { id: 443, reading: 'おとうとさん', japanese: 'おとうとさん', meaning: 'Adik laki-laki (orang lain)' },
  { id: 444, reading: 'おねえさん', japanese: 'おねえさん', meaning: 'Kakak perempuan (orang lain)' },
  { id: 445, reading: 'おにいさん', japanese: 'おにいさん', meaning: 'Kakak laki-laki (orang lain)' },
  { id: 446, 'reading': 'ごきょうだい', 'japanese': 'ごきょうだい', 'meaning': 'Saudara kandung (orang lain)' },
  { id: 447, 'reading': 'おくさん', 'japanese': 'おくさん', 'meaning': 'Istri (orang lain)' },
  { id: 448, 'reading': 'ごふうふ', 'japanese': 'ごふうふ', 'meaning': 'Pasangan suami istri (orang lain)' },
  { id: 449, 'reading': 'むすめさん', 'japanese': 'むすめさん', 'meaning': 'Anak perempuan (orang lain)' },
  { id: 450, 'reading': 'むすこさん', 'japanese': 'むすこさん', 'meaning': 'Anak laki-laki (orang lain)' },
  { id: 451, 'reading': 'おこさん', 'japanese': 'おこさん', 'meaning': 'Anak (orang lain)' },
];

const chapter8Words: VocabularyItem[] = [
  { id: 452, reading: 'ハンサム（な）', japanese: 'ハンサム（な）', meaning: 'Tampan / gagah / ganteng' },
  { id: 453, reading: 'きれい（な）', japanese: 'きれい（な）', meaning: 'Cantik / bersih' },
  { id: 454, reading: 'しずか（な）', japanese: '静か（な）', meaning: 'Sunyi / tenang' },
  { id: 455, reading: 'にぎやか（な）', japanese: 'にぎやか（な）', meaning: 'Ramai' },
  { id: 456, reading: 'ゆうめい（な）', japanese: '有名（な）', meaning: 'Terkenal' },
  { id: 457, reading: 'しんせつ（な）', japanese: '親切（な）', meaning: 'Baik hati' },
  { id: 458, reading: 'げんき（な）', japanese: '元気（な）', meaning: 'Sehat' },
  { id: 459, reading: 'ひま（な）', japanese: '暇（な）', meaning: 'Senggang' },
  { id: 460, reading: 'べんり（な）', japanese: '便利（な）', meaning: 'Praktis' },
  { id: 461, reading: 'すてき（な）', japanese: 'すてき（な）', meaning: 'Bagus' },
  { id: 462, reading: 'おおきい', japanese: '大きい', meaning: 'Besar' },
  { id: 463, reading: 'ちいさい', japanese: '小さい', meaning: 'Kecil' },
  { id: 464, reading: 'あたらしい', japanese: '新しい', meaning: 'Baru' },
  { id: 465, reading: 'ふるい', japanese: '古い', meaning: 'Lama / tua' },
  { id: 466, reading: 'いい（よい）', japanese: 'いい（よい）', meaning: 'Baik / bagus' },
  { id: 467, reading: 'わるい', japanese: '悪い', meaning: 'Jelek' },
  { id: 468, reading: 'あつい', japanese: '暑い', meaning: 'Panas' },
  { id: 469, reading: 'さむい', japanese: '寒い', meaning: 'Dingin suhu' },
  { id: 470, reading: 'つめたい', japanese: '冷たい', meaning: 'Dingin benda' },
  { id: 471, reading: 'むずかしい', japanese: '難しい', meaning: 'Sulit / susah' },
  { id: 472, reading: 'やさしい', japanese: '易しい', meaning: 'Mudah / gampang' },
  { id: 473, reading: 'たかい', japanese: '高い', meaning: 'Mahal / tinggi' },
  { id: 474, reading: 'やすい', japanese: '安い', meaning: 'Murah' },
  { id: 475, reading: 'ひくい', japanese: '低い', meaning: 'Rendah' },
  { id: 476, reading: 'おもしろい', japanese: 'おもしろい', meaning: 'Menarik' },
  { id: 477, reading: 'おいしい', japanese: 'おいしい', meaning: 'Enak' },
  { id: 478, reading: 'いそがしい', japanese: '忙しい', meaning: 'Sibuk' },
  { id: 479, reading: 'たのしい', japanese: '楽しい', meaning: 'Senang' },
  { id: 480, reading: 'しろい', japanese: '白い', meaning: 'Putih' },
  { id: 481, reading: 'くろい', japanese: '黒い', meaning: 'Hitam' },
  { id: 482, reading: 'あかい', japanese: '赤い', meaning: 'Merah' },
  { id: 483, reading: 'あおい', japanese: '青い', meaning: 'Biru' },
  { id: 484, reading: 'さくら', japanese: '桜', meaning: 'Sakura' },
  { id: 485, reading: 'やま', japanese: '山', meaning: 'Gunung' },
  { id: 486, reading: 'まち', japanese: '町', meaning: 'Kota' },
  { id: 487, reading: 'たべもの', japanese: '食べ物', meaning: 'Makanan' },
  { id: 488, reading: 'ところ', japanese: '所', meaning: 'Tempat' },
  { id: 489, reading: 'りょう', japanese: '寮', meaning: 'Asrama' },
  { id: 490, reading: 'レストラン', japanese: 'レストラン', meaning: 'Restoran' },
  { id: 491, reading: 'せいかつ', japanese: '生活', meaning: 'Kehidupan' },
  { id: 492, reading: 'しごと', japanese: '仕事', meaning: 'Pekerjaan' },
  { id: 493, reading: 'どう', japanese: 'どう', meaning: 'Bagaimana?' },
  { id: 494, reading: 'どんな～', japanese: 'どんな～', meaning: 'Yang bagaimana ?' },
  { id: 495, reading: 'とても', japanese: 'とても', meaning: 'Sangat / ~sekali' },
  { id: 496, reading: 'あまり', japanese: 'あまり', meaning: 'Tidak begitu ~ / kurang begitu ~' },
  { id: 497, reading: 'そして', japanese: 'そして', meaning: 'Kemudian' },
  { id: 498, reading: '～が～', japanese: '～が～', meaning: 'Tetapi' },
  { id: 499, reading: 'おげんきですか', japanese: 'お元気ですか', meaning: 'Apa kabar ?' },
  { id: 500, reading: 'そうですね', japanese: 'そうですね', meaning: 'Bagaimana ya?' },
  { id: 501, reading: '～もういっぱいいかがですか', japanese: '～もういっぱいいかがですか', meaning: 'Mau nambah secangkir lagi ?' },
  { id: 502, reading: '（いいえ）けっこうです', japanese: '（いいえ）けっこうです', meaning: 'Cukup' },
  { id: 503, reading: 'そろそろしつれいします', japanese: 'そろそろ失礼します', meaning: 'Maaf saya mau pamit dulu' },
  { id: 504, reading: 'いいえ', japanese: 'いいえ', meaning: 'Sama-sama' },
  { id: 505, reading: 'またいらっしゃってください', japanese: 'またいらっしゃってください', meaning: 'Silakan datang lagi' },
  { id: 506, reading: 'シャンハイ', japanese: 'シャンハイ', meaning: 'Shanghai' },
  { id: 507, reading: 'みどり', japanese: 'みどり', meaning: 'Hijau' },
  { id: 508, reading: 'むらさき', japanese: 'むらさき', meaning: 'Ungu' },
  { id: 509, reading: 'きいろい', japanese: 'きいろい', meaning: 'Kuning' },
  { id: 510, reading: 'ちゃいろい', japanese: 'ちゃいろい', meaning: 'Coklat' },
  { id: 511, reading: 'ピンク', japanese: 'ピンク', meaning: 'Merah muda' },
  { id: 512, reading: 'オレンジ', japanese: 'オレンジ', meaning: 'Oranye' },
  { id: 513, reading: 'グレー', japanese: 'グレー', meaning: 'Abu-abu' },
  { id: 514, reading: 'ベージュ', japanese: 'ベージュ', meaning: 'Krem' },
  { id: 515, reading: 'はる', japanese: '春', meaning: 'Musim semi' },
  { id: 516, reading: 'なつ', japanese: '夏', meaning: 'Musim panas' },
  { id: 517, reading: 'あき', japanese: '秋', meaning: 'Musim gugur' },
  { id: 518, reading: 'ふゆ', japanese: '冬', meaning: 'Musim dingin' },
];

const chapter9Words: VocabularyItem[] = [
  { id: 519, reading: 'わかります', japanese: '分かります', meaning: 'Mengerti' },
  { id: 520, reading: 'あります', japanese: 'あります', meaning: 'Ada / mempunyai' },
  { id: 521, reading: 'すき（な）', japanese: '好きな', meaning: 'Suka , gemar' },
  { id: 522, reading: 'きらい（な）', japanese: '嫌いな', meaning: 'Benci' },
  { id: 523, reading: 'じょうず（な）', japanese: '上手な', meaning: 'Pandai , pintar' },
  { id: 524, reading: 'へた（な）', japanese: '下手な', meaning: 'Tidak pandai , tidak pintar , bodoh' },
  { id: 525, reading: 'のみもの', japanese: '飲み物', meaning: 'Minuman' },
  { id: 526, reading: 'りょうり', japanese: '料理', meaning: 'Masakan' },
  { id: 527, reading: 'スポーツ', japanese: 'スポーツ', meaning: 'Olahraga' },
  { id: 528, reading: 'やきゅう', japanese: '野球', meaning: 'Baseball' },
  { id: 529, reading: 'ダンス', japanese: 'ダンス', meaning: 'Dansa' },
  { id: 530, reading: 'りょこう', japanese: '旅行', meaning: 'Tamasya' },
  { id: 531, reading: 'おんがく', japanese: '音楽', meaning: 'Musik' },
  { id: 532, reading: 'うた', japanese: '歌', meaning: 'Lagu' },
  { id: 533, reading: 'クラシック', japanese: 'クラシック', meaning: 'Klasik' },
  { id: 534, reading: 'ジャズ', japanese: 'ジャズ', meaning: 'Jaz' },
  { id: 535, reading: 'コンサート', japanese: 'コンサート', meaning: 'Konser' },
  { id: 536, reading: 'カラオケ', japanese: 'カラオケ', meaning: 'Karaoke' },
  { id: 537, reading: 'かぶき', japanese: '歌舞伎', meaning: 'Kabuki (drama tradisional jepang)' },
  { id: 538, reading: 'え', japanese: '絵', meaning: 'Gambar' },
  { id: 539, reading: 'じ', japanese: '字', meaning: 'Huruf' },
  { id: 540, reading: 'かんじ', japanese: '漢字', meaning: 'Kanji' },
  { id: 541, reading: 'ひらがな', japanese: 'ひらがな', meaning: 'Hiragana' },
  { id: 542, reading: 'かたかな', japanese: 'かたかな', meaning: 'Katakana' },
  { id: 543, reading: 'ローマじ', japanese: 'ローマじ', meaning: 'Huruf latin' },
  { id: 544, reading: 'こまかいおかね', japanese: '細かいお金', meaning: 'Uang kecil, receh' },
  { id: 545, reading: 'チケット', japanese: 'チケット', meaning: 'Tiket' },
  { id: 546, reading: 'じかん', japanese: '時間', meaning: 'Waktu' },
  { id: 547, reading: 'ようじ', japanese: '用事', meaning: 'Urusan' },
  { id: 548, reading: 'やくそく', japanese: '約束', meaning: 'Janji' },
  { id: 549, reading: 'アルバイト', japanese: 'アルバイト', meaning: 'Kerja paruh waktu' },
  { id: 550, reading: 'ごしゅじん', japanese: 'ご主人', meaning: 'Suami orang lain' },
  { id: 551, reading: 'おっと／しゅじん', japanese: '夫／主人', meaning: 'Suami' },
  { id: 552, reading: 'おくさん', japanese: '奥さん', meaning: 'Istri orang lain' },
  { id: 553, reading: 'つま／かない', japanese: '妻／家内', meaning: 'Istri' },
  { id: 554, reading: 'こども', japanese: '子供', meaning: 'Anak' },
  { id: 555, reading: 'よく', japanese: 'よく', meaning: 'Dengan baik' },
  { id: 556, reading: 'だいたい', japanese: 'だいたい', meaning: 'Kira-kira' },
  { id: 557, reading: 'たくさん', japanese: 'たくさん', meaning: 'Banyak' },
  { id: 558, reading: 'すこし', japanese: '少し', meaning: 'Sedikit' },
  { id: 559, reading: 'ぜんぜん', japanese: '全然', meaning: 'Sama sekali' },
  { id: 560, reading: 'はやく', japanese: '早く／速く', meaning: 'Dengan Cepat' },
  { id: 561, reading: '～から', japanese: '～から', meaning: 'Karena' },
  { id: 562, reading: 'どうして', japanese: 'どうして', meaning: 'Kenapa' },
  { id: 563, reading: 'かしてください', japanese: '貸してください', meaning: 'Tolong pinjamkan' },
  { id: 564, reading: 'いいですよ', japanese: 'いいですよ', meaning: 'Boleh' },
  { id: 565, reading: 'ざんねんです', japanese: '残念です', meaning: 'Sayang sekali' },
  { id: 566, reading: 'いっしょにいかがですか', japanese: 'いっしょにいかがですか', meaning: 'Bagaimana kalau bersama-sama' },
  { id: 567, reading: '～ちょっと。。。。', japanese: '～ちょっと。。。。', meaning: 'Maaf, saya tidak bisa' },
  { id: 568, reading: 'だめですか', japanese: 'だめですか', meaning: 'Tidak bisa ya / tidak boleh ya' },
  { id: 569, reading: 'またこんどおねがいします', japanese: 'また今度お願いします', meaning: 'Maaf lain kali saja' },
  { id: 570, reading: 'ポップス', japanese: 'ポップス', meaning: 'Pop' },
  { id: 571, reading: 'ロック', japanese: 'ロック', meaning: 'Rock' },
  { id: 572, reading: 'ラテン', japanese: 'ラテン', meaning: 'Musik latin' },
  { id: 573, reading: 'みんよう', japanese: '民謡', meaning: 'Musik rakyat / nyanyian daerah' },
  { id: 574, reading: 'えんか', japanese: '演歌', meaning: 'Lagu tradisional jepang populer' },
  { id: 575, reading: 'ミュージカル', japanese: 'ミュージカル', meaning: 'Drama musikal' },
  { id: 576, reading: 'オペラ', japanese: 'オペラ', meaning: 'Opera' },
  { id: 577, reading: 'ホラー', japanese: 'ホラー', meaning: 'Film horor' },
  { id: 578, reading: 'アニメ', japanese: 'アニメ', meaning: 'Film kartun , animasi' },
  { id: 579, reading: 'ドキュメンタリー', japanese: 'ドキュメンタリー', meaning: 'Film dokumentasi' },
  { id: 580, reading: 'れんあい', japanese: '恋愛', meaning: 'Film percintaan' },
  { id: 581, reading: 'ミステリー', japanese: 'ミステリー', meaning: 'Film misteri' },
  { id: 582, reading: 'ぶんげい', japanese: '文芸', meaning: 'Film kesusastraan' },
  { id: 583, reading: 'せんそう', japanese: '戦争', meaning: 'Film peperangan' },
  { id: 584, reading: 'アクション', japanese: 'アクション', meaning: 'Film action' },
  { id: 585, reading: 'きげき', japanese: '喜劇', meaning: 'Film komedi' },
  { id: 586, reading: 'ソフトボール', japanese: 'ソフトボール', meaning: 'Softball' },
  { id: 587, reading: 'サッカー', japanese: 'サッカー', meaning: 'Sepak bola' },
  { id: 588, reading: 'ラグビー', japanese: 'ラグビー', meaning: 'Rugby' },
  { id: 589, reading: 'バレーボール', japanese: 'バレーボール', meaning: 'Voli' },
  { id: 590, reading: 'テニス', japanese: 'テニス', meaning: 'Tenis' },
  { id: 591, reading: 'ボウリング', japanese: 'ボウリング', meaning: 'Bowling' },
  { id: 592, reading: 'スキー', japanese: 'スキー', meaning: 'Sky' },
  { id: 593, reading: 'スケート', japanese: 'スケート', meaning: 'Skate' },
  { id: 594, reading: 'たっきゅう／ピンポン', japanese: '卓球', meaning: 'Pingpong' },
  { id: 595, reading: 'すもう', japanese: '相撲', meaning: 'Sumo' },
  { id: 596, reading: 'じゅうどう', japanese: '柔道', meaning: 'Judo' },
  { id: 597, reading: 'けんどう', japanese: '剣道', meaning: 'Kendo' },
  { id: 598, reading: 'すいえい', japanese: '水泳', meaning: 'Renang' },
];

const chapter10Words: VocabularyItem[] = [
  { id: 599, reading: 'あります', japanese: 'あります', meaning: 'Ada (benda mati)' },
  { id: 600, reading: 'います', japanese: 'います', meaning: 'Ada (benda hidup)' },
  { id: 601, reading: 'いろいろ（な）', japanese: 'いろいろ（な）', meaning: 'Berbagai / macam-macam' },
  { id: 602, reading: 'おとこのひと', japanese: '男の人', meaning: 'Orang laki-laki' },
  { id: 603, reading: 'おんなのひと', japanese: '女の人', meaning: 'Orang perempuan' },
  { id: 604, reading: 'おとこのこ', japanese: '男の子', meaning: 'Anak laki-laki' },
  { id: 605, reading: 'おんなのこ', japanese: '女の子', meaning: 'Anak perempuan' },
  { id: 606, reading: 'いぬ', japanese: '犬', meaning: 'Anjing' },
  { id: 607, reading: 'ねこ', japanese: '猫', meaning: 'Kucing' },
  { id: 608, reading: 'パンダ', japanese: 'パンダ', meaning: 'Panda' },
  { id: 609, reading: 'ぞう', japanese: '象', meaning: 'Gajah' },
  { id: 610, reading: 'き', japanese: '木', meaning: 'Pohon' },
  { id: 611, reading: 'もの', japanese: '物', meaning: 'Barang' },
  { id: 612, reading: 'でんち', japanese: '電池', meaning: 'Baterai' },
  { id: 613, reading: 'はこ', japanese: '箱', meaning: 'Kotak' },
  { id: 614, reading: 'スイッチ', japanese: 'スイッチ', meaning: 'Saklar' },
  { id: 615, reading: 'れいぞうこ', japanese: '冷蔵庫', meaning: 'Kulkas' },
  { id: 616, reading: 'テーブル', japanese: 'テーブル', meaning: 'Meja makan' },
  { id: 617, reading: 'ベッド', japanese: 'ベッド', meaning: 'Tempat tidur' },
  { id: 618, reading: 'たな', japanese: '棚', meaning: 'Lemari' },
  { id: 619, reading: 'ドア', japanese: 'ドア', meaning: 'Pintu' },
  { id: 620, reading: 'まど', japanese: '窓', meaning: 'Jendela' },
  { id: 621, reading: 'ポスト', japanese: 'ポスト', meaning: 'Kotak surat' },
  { id: 622, reading: 'ビル', japanese: 'ビル', meaning: 'Gedung' },
  { id: 623, reading: 'ＡＴＭ', japanese: 'ＡＴＭ', meaning: 'Atm' },
  { id: 624, reading: 'コンビニ', japanese: 'コンビニ', meaning: 'Toko 24 jam' },
  { id: 625, reading: 'こうえん', japanese: '公園', meaning: 'Taman' },
  { id: 626, reading: 'きっさてん', japanese: '喫茶店', meaning: 'Coffe shop / cafe' },
  { id: 627, reading: '～や', japanese: '～屋', meaning: 'Toko ~' },
  { id: 628, reading: 'のりば', japanese: '乗り場', meaning: 'Tempat naik' },
  { id: 629, reading: 'けん', japanese: '県', meaning: 'Prefektur' },
  { id: 630, reading: 'うえ', japanese: '上', meaning: 'Atas' },
  { id: 631, reading: 'した', japanese: '下', meaning: 'Bawah' },
  { id: 632, reading: 'まえ', japanese: '前', meaning: 'Depan' },
  { id: 633, reading: 'うしろ', japanese: '後ろ', meaning: 'Belakang' },
  { id: 634, reading: 'みぎ', japanese: '右', meaning: 'Kanan' },
  { id: 635, reading: 'ひだり', japanese: '左', meaning: 'Kiri' },
  { id: 636, reading: 'なか', japanese: '中', meaning: 'Dalam' },
  { id: 637, reading: 'そと', japanese: '外', meaning: 'Luar' },
  { id: 638, reading: 'となり', japanese: '隣', meaning: 'Samping / sebelah' },
  { id: 639, reading: 'ちかく', japanese: '近く', meaning: 'Dekat' },
  { id: 640, reading: 'あいだ', japanese: '間', meaning: 'Antara' },
  { id: 641, reading: 'どうもすみません', japanese: 'どうもすみません', meaning: 'Maaf / terima kasih banyak' },
  { id: 642, reading: 'ナンプラー', japanese: 'ナンプラー', meaning: 'Kecap ikan' },
  { id: 643, reading: 'コーナー', japanese: 'コーナー', meaning: 'Tempat / bagian penjualan' },
  { id: 644, reading: 'いちばんした', japanese: '一番下', meaning: 'Paling bawah' },
  { id: 645, reading: 'げんかん', japanese: '玄関', meaning: 'Pintu masuk' },
  { id: 646, reading: 'ふろば', japanese: '風呂場', meaning: 'Kamar mandi' },
  { id: 647, reading: 'せんめんじょ', japanese: '洗面所', meaning: 'Tempat cuci tangan' },
  { id: 648, reading: 'だいどころ', japanese: '台所', meaning: 'Dapur' },
  { id: 649, reading: 'しょくどう', japanese: '食堂', meaning: 'Kantin / ruang makan' },
  { id: 650, reading: 'いま', japanese: '居間', meaning: 'Ruang tamu' },
  { id: 651, reading: 'しんしつ', japanese: '寝室', meaning: 'Kamar tidur' },
  { id: 652, reading: 'ろうか', japanese: '廊下', meaning: 'Koridor' },
  { id: 653, reading: 'ベランダ', japanese: 'ベランダ', meaning: 'teras' },
];

const chapter11Words: VocabularyItem[] = [
  { id: 654, reading: 'います', japanese: 'います', meaning: 'Ada / mempunyai' },
  { id: 655, reading: 'かかります', japanese: 'かかります', meaning: 'Memerlukan waktu' },
  { id: 656, reading: 'やすみます', japanese: '休みます', meaning: 'Tidak masuk kerja / libur' },
  { id: 657, reading: 'ひとつ', japanese: 'ひとつ', meaning: '1 buah' },
  { id: 658, reading: 'ふたつ', japanese: 'ふたつ', meaning: '2 buah' },
  { id: 659, reading: 'みっつ', japanese: 'みっつ', meaning: '3 buah' },
  { id: 660, reading: 'よっつ', japanese: 'よっつ', meaning: '4 buah' },
  { id: 661, reading: 'いつつ', japanese: 'いつつ', meaning: '5 buah' },
  { id: 662, reading: 'むっつ', japanese: 'むっつ', meaning: '6 buah' },
  { id: 663, reading: 'ななつ', japanese: 'ななつ', meaning: '7 buah' },
  { id: 664, reading: 'やっつ', japanese: 'やっつ', meaning: '8 buah' },
  { id: 665, reading: 'ここのつ', japanese: 'ここのつ', meaning: '9 buah' },
  { id: 666, reading: 'とお', japanese: 'とお', meaning: '10 buah' },
  { id: 667, reading: 'いくつ', japanese: 'いくつ', meaning: 'Berapa buah ?' },
  { id: 668, reading: 'ひとり', japanese: 'ひとり', meaning: '1 orang' },
  { id: 669, reading: 'ふたり', japanese: 'ふたり', meaning: '2 orang' },
  { id: 670, reading: '～にん', japanese: '～人', meaning: '~ orang' },
  { id: 671, reading: '～だい', japanese: '～台', meaning: '~ unit' },
  { id: 672, reading: '～まい', japanese: '～枚', meaning: '~ lembar' },
  { id: 673, reading: '～かい', japanese: '～回', meaning: '~ kali' },
  { id: 674, reading: 'りんご', japanese: 'りんご', meaning: 'Apel' },
  { id: 675, reading: 'みかん', japanese: 'みかん', meaning: 'Jeruk' },
  { id: 676, reading: 'サンドイッチ', japanese: 'サンドイッチ', meaning: 'Sandwich' },
  { id: 677, reading: 'カレー', japanese: 'カレー', meaning: 'Kare' },
  { id: 678, reading: 'アイスクリーム', japanese: 'アイスクリーム', meaning: 'Es krim' },
  { id: 679, reading: 'きって', japanese: '切手', meaning: 'Perangko' },
  { id: 680, reading: 'はがき', japanese: 'はがき', meaning: 'Kartu pos' },
  { id: 681, reading: 'ふうとう', japanese: '封筒', meaning: 'Amplop' },
  { id: 682, reading: 'がいこく', japanese: '外国', meaning: 'Luar negeri' },
  { id: 683, reading: 'りゅうがくせい', japanese: '留学生', meaning: 'Pelajar asing' },
  { id: 684, reading: 'クラス', japanese: 'クラス', meaning: 'Kelas' },
  { id: 685, reading: '～じかん', japanese: '～時間', meaning: '~ jam' },
  { id: 686, reading: '～しゅうかん', japanese: '～週間', meaning: '~ minggu' },
  { id: 687, reading: '～かげつ', japanese: '～か月', meaning: '~ bulan' },
  { id: 688, reading: '～ねん', japanese: '～年', meaning: '~ tahun' },
  { id: 689, reading: '～ぐらい', japanese: '～ぐらい', meaning: 'Kira-kira ~' },
  { id: 690, reading: 'どのくらい', japanese: 'どのくらい', meaning: 'Berapa lama ?' },
  { id: 691, reading: 'ぜんぶで', japanese: '全部で', meaning: 'Semuanya' },
  { id: 692, reading: 'みんな', japanese: 'みんな', meaning: 'Semua' },
  { id: 693, reading: '～だけ', japanese: '～だけ', meaning: 'Hanya ~' },
  { id: 694, reading: 'かしこまりました', japanese: 'かしこまりました', meaning: 'Baik / mengerti' },
  { id: 695, reading: 'いいてんきですね', japanese: 'いい天気ですね', meaning: 'Cuacanya bagus ya...' },
  { id: 696, reading: 'おでかけですか', japanese: 'お出かけですか', meaning: 'Mau keluar ?' },
  { id: 697, reading: 'いってらっしゃい', japanese: '行ってらっしゃい', meaning: 'Hati-hati (berangkatnya)' },
  { id: 698, reading: 'いってきます', japanese: '行ってきます', meaning: 'Saya berangkat' },
  { id: 699, reading: 'ふなびん', japanese: '船便', meaning: 'Pos laut' },
  { id: 700, reading: 'こうくうびん', japanese: '航空便', meaning: 'Pos udara' },
  { id: 701, reading: 'エアメール', japanese: 'エアメール', meaning: 'Pos udara' },
  { id: 702, reading: 'オーストラリア', japanese: 'オーストラリア', meaning: 'Australia' },
  { id: 703, reading: 'ていしょく', japanese: '定食', meaning: 'Makanan paket' },
  { id: 704, reading: 'ランチ', japanese: 'ランチ', meaning: 'Makan siang' },
  { id: 705, reading: 'てんどん', japanese: '天どん', meaning: 'Semangkuk Nasi dan tempura' },
  { id: 706, reading: 'おやこどん', japanese: 'おやこどん', meaning: 'Semangkuk Nasi, daging ayam dan telur' },
  { id: 707, reading: 'ぎゅうどん', japanese: '牛どん', meaning: 'Semangkuk nasi dan daging sapi' },
  { id: 708, reading: 'やきにく', japanese: '焼肉', meaning: 'Daging panggang' },
  { id: 709, reading: 'やさいため', japanese: '野菜ため', meaning: 'Sayur goreng' },
  { id: 710, reading: 'つけもの', japanese: '漬物', meaning: 'Asinan' },
  { id: 711, reading: 'みそしる', japanese: 'みそ汁', meaning: 'Sup miso' },
  { id: 712, reading: 'おにぎり', japanese: 'おにぎり', meaning: 'Nasi kepal' },
  { id: 713, reading: 'てんぷら', japanese: 'てんぷら', meaning: 'Tempura' },
  { id: 714, reading: 'すし', japanese: 'すし', meaning: 'Nasi dicampur cuka dan diberi ikan mentah' },
  { id: 715, reading: 'うどん', japanese: 'うどん', meaning: 'Mie jepang ukuran besar' },
  { id: 716, reading: 'そば', japanese: 'そば', meaning: 'Mie jepang warna abu-abu' },
  { id: 717, reading: 'ラーメン', japanese: 'ラーメン', meaning: 'Mie jepang ukuran biasa' },
  { id: 718, reading: 'やきそば', japanese: '焼きそば', meaning: 'Mie goreng jepang' },
  { id: 719, reading: 'おこのみやき', japanese: 'お好み焼き', meaning: 'Gorengan dicampur daging di loyang' },
  { id: 720, reading: 'カレーライス', japanese: 'カレーライス', meaning: 'Nasi kare' },
  { id: 721, reading: 'ハンバーグ', japanese: 'ハンバーグ', meaning: 'hamburger' },
  { id: 722, reading: 'コロッケ', japanese: 'コロッケ', meaning: 'Kroket' },
  { id: 723, reading: 'えびフライ', japanese: 'えびフライ', meaning: 'Udang goreng tepung' },
  { id: 724, reading: 'フライドチキン', japanese: 'フライドチキン', meaning: 'Ayam goreng' },
  { id: 725, reading: 'サラダ', japanese: 'サラダ', meaning: 'Salad' },
  { id: 726, reading: 'スープ', japanese: 'スープ', meaning: 'Sup' },
  { id: 727, reading: 'スパゲッティ', japanese: 'スパゲッティ', meaning: 'Spageti' },
  { id: 728, reading: 'ピザ', japanese: 'ピザ', meaning: 'Pizza' },
  { id: 729, reading: 'トースト', japanese: 'トースト', meaning: 'Roti panggang' },
  { id: 730, reading: 'コーヒー', japanese: 'コーヒー', meaning: 'Kopi' },
  { id: 731, reading: 'こうちゃ', japanese: '紅茶', meaning: 'Teh' },
  { id: 732, reading: 'ココア', japanese: 'ココア', meaning: 'Minuman coklat' },
  { id: 733, reading: 'ジュース', japanese: 'ジュース', meaning: 'Jus' },
  { id: 734, reading: 'コーラ', japanese: 'コーラ', meaning: 'Coca cola' },
];

const chapter12Words: VocabularyItem[] = [
  { id: 735, reading: 'かんたん（な）', japanese: '簡単な', meaning: 'Mudah, gampang' },
  { id: 736, reading: 'ちかい', japanese: '近い', meaning: 'Dekat' },
  { id: 737, reading: 'とおい', japanese: '遠い', meaning: 'Jauh' },
  { id: 738, reading: 'はやい', japanese: '早い，速い', meaning: 'Cepat' },
  { id: 739, reading: 'おそい', japanese: '遅い', meaning: 'Lambat' },
  { id: 740, reading: 'おおい', japanese: '多い', meaning: 'Banyak' },
  { id: 741, reading: 'すくない', japanese: '少ない', meaning: 'Sedikit' },
  { id: 742, reading: 'あたたかい', japanese: '暖かい、温かい', meaning: 'Hangat' },
  { id: 743, reading: 'すずしい', japanese: '涼しい', meaning: 'Sejuk' },
  { id: 744, reading: 'あまい', japanese: '甘い', meaning: 'Manis' },
  { id: 745, reading: 'からい', japanese: '辛い', meaning: 'Pedas' },
  { id: 746, reading: 'おもい', japanese: '重い', meaning: 'Berat' },
  { id: 747, reading: 'かるい', japanese: '軽い', meaning: 'Ringan' },
  { id: 748, reading: 'いい', japanese: 'いい', meaning: 'Lebih baik' },
  { id: 749, reading: 'きせつ', japanese: '季節', meaning: 'Musim' },
  { id: 750, reading: 'てんき', japanese: '天気', meaning: 'Cuaca' },
  { id: 751, reading: 'あめ', japanese: '雨', meaning: 'Hujan' },
  { id: 752, reading: 'ゆき', japanese: '雪', meaning: 'Salju' },
  { id: 753, reading: 'くもり', japanese: '曇り', meaning: 'Mendung' },
  { id: 754, reading: 'ホテル', japanese: 'ホテル', meaning: 'Hotel' },
  { id: 755, reading: 'くうこう', japanese: '空港', meaning: 'Bandara' },
  { id: 756, reading: 'うみ', japanese: '海', meaning: 'Laut' },
  { id: 757, reading: 'せかい', japanese: '世界', meaning: 'Dunia' },
  { id: 758, reading: 'パーティー', japanese: 'パーティー', meaning: 'Pesta' },
  { id: 759, reading: 'まつり', japanese: '祭り', meaning: 'Perayaan' },
  { id: 760, reading: 'レモン', japanese: 'レモン', meaning: 'Lemon' },
  { id: 761, reading: 'いけばな', japanese: '生け花', meaning: 'Seni merangkai bunga' },
  { id: 762, reading: 'もみじ', japanese: '紅葉', meaning: 'Maple' },
  { id: 763, reading: 'どちら', japanese: 'どちら', meaning: 'Yang mana' },
  { id: 764, reading: 'どちらも', japanese: 'どちらも', meaning: 'Dua-duanya / yang mana saja' },
  { id: 765, reading: 'いちばん', japanese: 'いちばん', meaning: 'Yang paling' },
  { id: 766, reading: 'ずっと', japanese: 'ずっと', meaning: 'Selamanya' },
  { id: 767, reading: 'はじめて', japanese: '初めて', meaning: 'Pertama kali' },
  { id: 768, reading: 'ただいま', japanese: 'ただいま', meaning: 'Saya pulang / saya kembali' },
  { id: 769, reading: 'おかえりなさい', japanese: 'お帰りなさい', meaning: 'Sudah pulang ya...' },
  { id: 770, reading: 'わあ、すごいひとですね', japanese: 'わあ、すごいひとですね', meaning: 'Wah...banyak orang' },
  { id: 771, reading: 'つかれました', japanese: '疲れました', meaning: 'Capek / lelah' },
  { id: 772, reading: 'ホンコン', japanese: 'ホンコン', meaning: 'Hongkong' },
  { id: 773, reading: 'シンガポール', japanese: 'シンガポール', meaning: 'Singapura' },
  { id: 774, reading: 'めいしょ', japanese: '名所', meaning: 'Tempat terkenal' },
];

const chapter13Words: VocabularyItem[] = [
  { id: 775, reading: 'あそびます', japanese: '遊びます', meaning: 'Bermain' },
  { id: 776, reading: 'およぎます', japanese: '泳ぎます', meaning: 'Berenang' },
  { id: 777, reading: 'むかえます', japanese: '迎えます', meaning: 'Menjemput' },
  { id: 778, reading: 'つかれます', japanese: '疲れます', meaning: 'Lelah' },
  { id: 779, reading: 'けっこんします', japanese: '結婚します', meaning: 'Menikah' },
  { id: 780, reading: 'かいものします', japanese: '買い物します', meaning: 'Berbelanja' },
  { id: 781, reading: 'しょくじします', japanese: '食事します', meaning: 'Makan bersama' },
  { id: 782, reading: 'さんぽします', japanese: '散歩します', meaning: 'Jalan-jalan' },
  { id: 783, reading: 'たいへん（な）', japanese: '大変な', meaning: 'Susah, berat' },
  { id: 784, reading: 'ほしい', japanese: '欲しい', meaning: 'Ingin' },
  { id: 785, reading: 'ひろい', japanese: '広い', meaning: 'Luas' },
  { id: 786, reading: 'せまい', japanese: '狭い', meaning: 'Sempit' },
  { id: 787, reading: 'プール', japanese: 'プール', meaning: 'Kolam renang' },
  { id: 788, reading: 'かわ', japanese: '川', meaning: 'Sungai' },
  { id: 789, reading: 'びじゅつ', japanese: '美術', meaning: 'Seni' },
  { id: 790, reading: 'つり', japanese: '釣り', meaning: 'Pancing , memancing' },
  { id: 791, reading: 'スキー', japanese: 'スキー', meaning: 'Ski' },
  { id: 792, reading: 'しゅうまつ', japanese: '週末', meaning: 'Akhir pekan' },
  { id: 793, reading: 'おしょうがつ', japanese: 'お正月', meaning: 'Tahun baru' },
  { id: 794, reading: '～ごろ', japanese: '～ごろ', meaning: 'Kira-kira , sekitar' },
  { id: 795, reading: 'なにか', japanese: '何か', meaning: 'Sesuatu' },
  { id: 796, reading: 'どこか', japanese: 'どこか', meaning: 'Suatu tempat' },
  { id: 797, reading: 'のどがかわきます', japanese: 'のどがかわきます', meaning: 'Haus' },
  { id: 798, reading: 'おなかがすきます', japanese: 'おなかがすきます', meaning: 'Lapar' },
  { id: 799, reading: 'そうしましょう', japanese: 'そうしましょう', meaning: 'Ya ayo' },
  { id: 800, reading: 'ごちゅうもんは', japanese: 'ご注文は', meaning: 'Mau pesan apa?' },
  { id: 801, reading: 'おまちください', japanese: 'お待ちください', meaning: 'Tunggu sebentar' },
  { id: 802, reading: 'べつべつに', japanese: '別々に', meaning: 'Sendiri-sendiri / masing-masing' },
  { id: 803, reading: 'はくぶつかん', japanese: '博物館', meaning: 'Museum' },
  { id: 804, reading: 'びじゅつかん', japanese: '美術館', meaning: 'Gedung kesenian' },
  { id: 805, reading: 'としょかん', japanese: '図書館', meaning: 'Perpustakaan' },
  { id: 806, reading: 'えいがかん', japanese: '映画館', meaning: 'Bioskop' },
  { id: 807, reading: 'どうぶつえん', japanese: '動物園', meaning: 'Kebun binatang' },
  { id: 808, reading: 'しょくぶつえん', japanese: '植物園', meaning: 'Kebun raya' },
  { id: 809, reading: 'おてら', japanese: 'お寺', meaning: 'Kuil budha' },
  { id: 810, reading: 'じんじゃ', japanese: '神社', meaning: 'Kuil sinto' },
  { id: 811, reading: 'きょうかい', japanese: '教会', meaning: 'Gereja' },
  { id: 812, reading: 'たいしかん', japanese: '体育館', meaning: 'Kedutaan besar' },
  { id: 813, reading: 'にゅうこくかんりきょく', japanese: '入国管理局', meaning: 'Kantor imigrasi' },
  { id: 814, reading: 'しやくしょ', japanese: '市役所', meaning: 'Kantor balaikota' },
  { id: 815, reading: 'こうばん', japanese: '交番', meaning: 'Pos polisi' },
  { id: 816, reading: 'ちゅうしゃじょう', japanese: '駐車場', meaning: 'Tempat parkir' },
  { id: 817, reading: 'だいがく', japanese: '大学', meaning: 'Universitas' },
  { id: 818, reading: 'こうこう', japanese: '高校', meaning: 'Sma' },
  { id: 819, reading: 'ちゅうがっこう', japanese: '中学校', meaning: 'Smp' },
  { id: 820, reading: 'しょうがっこう', japanese: '小学校', meaning: 'Sd' },
  { id: 821, reading: 'ようちえん', japanese: '幼稚園', meaning: 'Tk' },
  { id: 822, reading: 'にくや', japanese: '肉屋', meaning: 'Toko daging' },
  { id: 823, reading: 'パンや', japanese: 'パンや', meaning: 'Toko roti' },
  { id: 824, reading: 'さかなや', japanese: '魚屋', meaning: 'Toko ikan' },
  { id: 825, reading: 'やおや', japanese: '八百屋', meaning: 'Toko sayuran' },
];


const allWords: VocabularyItem[] = [...chapter1Words, ...chapter2Words, ...chapter3Words, ...chapter4Words, ...chapter5Words, ...chapter6Words, ...chapter7Words, ...chapter8Words, ...chapter9Words, ...chapter10Words, ...chapter11Words, ...chapter12Words, ...chapter13Words];

export const chapters: Chapter[] = Array.from({ length: 50 }, (_, i) => {
  const chapterNumber = i + 1;
  let words: VocabularyItem[] = [];
  if (chapterNumber === 1) words = chapter1Words;
  if (chapterNumber === 2) words = chapter2Words;
  if (chapterNumber === 3) words = chapter3Words;
  if (chapterNumber === 4) words = chapter4Words;
  if (chapterNumber === 5) words = chapter5Words;
  if (chapterNumber === 6) words = chapter6Words;
  if (chapterNumber === 7) words = chapter7Words;
  if (chapterNumber === 8) words = chapter8Words;
  if (chapterNumber === 9) words = chapter9Words;
  if (chapterNumber === 10) words = chapter10Words;
  if (chapterNumber === 11) words = chapter11Words;
  if (chapterNumber === 12) words = chapter12Words;
  if (chapterNumber === 13) words = chapter13Words;

  return {
    chapter: chapterNumber,
    words: words,
  };
});

// For practice page, we can provide a flat list for simplicity of random selection
export const vocabularyList: VocabularyItem[] = allWords;


