export interface VocabularyItem {
  id: number;
  japanese: string;
  reading: string;
  meaning: string;
}

export interface Chapter {
  chapter: number;
  words: VocabularyItem[];
}

const chapter1Words: VocabularyItem[] = [
  { id: 1, reading: 'わたし', japanese: '私', meaning: 'Saya' },
  { id: 2, reading: 'あなた', japanese: 'あなた', meaning: 'Kamu' },
  { id: 3, reading: 'あのひと', japanese: 'あの人', meaning: 'Orang itu (biasa)' },
  { id: 4, reading: 'あのかた', japanese: 'あの方', meaning: 'Orang itu (sopan)' },
  { id: 5, reading: '～さん', japanese: '～さん', meaning: 'Saudara…….' },
  { id: 6, reading: '～ちゃん', japanese: '～ちゃん', meaning: 'Panggilan untuk anak laki/perempuan' },
  { id: 7, reading: '～じん', japanese: '～人', meaning: 'Orang…….' },
  { id: 8, reading: 'せんせい', japanese: '先生', meaning: 'Guru,dosen' },
  { id: 9, reading: 'きょうし', japanese: '教師', meaning: 'Guru,dosen (dipakai untuk kalangan sendiri)' },
  { id: 10, reading: 'がくせい', japanese: '学生', meaning: 'Siswa,murid' },
  { id: 11, reading: 'かいしゃいん', japanese: '会社員', meaning: 'Pegawai perusahaan' },
  { id: 12, reading: 'しゃいん', japanese: '社員', meaning: 'Pegawai perusahaan' },
  { id: 13, reading: 'ぎんこういん', japanese: '銀行員', meaning: 'Pegawai bank' },
  { id: 14, reading: 'いしゃ', japanese: '医者', meaning: 'Dokter' },
  { id: 15, reading: 'けんきゅうしゃ', japanese: '研究者', meaning: 'Peneliti' },
  { id: 16, reading: 'だいがく', japanese: '大学', meaning: 'Universitas' },
  { id: 17, reading: 'びょういん', japanese: '病院', meaning: 'Rumah sakit' },
  { id: 18, reading: 'だれ', japanese: 'だれ', meaning: 'Siapa (biasa)' },
  { id: 19, reading: 'どなた', japanese: 'どなた', meaning: 'Siapa (sopan)' },
  { id: 20, reading: '～さい', japanese: '～歳', meaning: 'Umur…..' },
  { id: 21, reading: 'なんさい', japanese: '何歳', meaning: 'Umur berapa?(biasa)' },
  { id: 22, reading: 'おいくつ', japanese: 'おいくつ', meaning: 'Umur berapa?(sopan)' },
  { id: 23, reading: 'はい', japanese: 'はい', meaning: 'Iya' },
  { id: 24, reading: 'いいえ', japanese: 'いいえ', meaning: 'Tidak' },
  { id: 25, reading: 'はじめまして', japanese: 'はじめまして', meaning: 'Perkenalkan' },
  { id: 26, reading: '～からきました', japanese: '～から来ました', meaning: 'Datang dari…..' },
  { id: 27, reading: 'どうぞよろしくおねがいします', japanese: 'どうぞよろしくお願します', meaning: 'Terimalah perkenalan saya' },
  { id: 28, reading: 'しつれいですが', japanese: '失礼ですが', meaning: 'Permisi' },
  { id: 29, reading: 'おなまえは', japanese: 'お名前は', meaning: 'Nama anda siapa?' },
  { id: 30, reading: 'アメリカ', japanese: 'アメリカ', meaning: 'Amerika' },
  { id: 31, reading: 'イギリス', japanese: 'イギリス', meaning: 'Inggris' },
  { id: 32, reading: 'インド', japanese: 'インド', meaning: 'India' },
  { id: 33, reading: 'インドネシア', japanese: 'インドネシア', meaning: 'Indonesia' },
  { id: 34, reading: 'かんこく', japanese: '韓国', meaning: 'Korea' },
  { id: 35, reading: 'ちゅうごく', japanese: '中国', meaning: 'China' },
  { id: 36, reading: 'ドイツ', japanese: 'ドイツ', meaning: 'Jerman' },
  { id: 37, reading: 'にほん', japanese: '日本', meaning: 'Jepang' },
  { id: 38, reading: 'フランス', japanese: 'フランス', meaning: 'Perancis' },
];

const chapter2Words: VocabularyItem[] = [
  { id: 39, reading: "これ", japanese: "これ", meaning: "Ini" },
  { id: 40, reading: "それ", japanese: "それ", meaning: "Itu (dekat)" },
  { id: 41, reading: "あれ", japanese: "あれ", meaning: "Itu (jauh)" },
  { id: 42, reading: "この～", japanese: "この～", meaning: "～ini" },
  { id: 43, reading: "その～", japanese: "その～", meaning: "～itu (dekat)" },
  { id: 44, reading: "あの～", japanese: "あの～", meaning: "～itu (jauh)" },
  { id: 45, reading: "ほん", japanese: "本", meaning: "Buku" },
  { id: 46, reading: "じしょ", japanese: "辞書", meaning: "Kamus" },
  { id: 47, reading: "ざっし", japanese: "雑誌", meaning: "Majalah" },
  { id: 48, reading: "しんぶん", japanese: "新聞", meaning: "Koran" },
  { id: 49, reading: "ノート", japanese: "ノート", meaning: "Buku catatan" },
  { id: 50, reading: "てちょう", japanese: "手帳", meaning: "Buku agenda" },
  { id: 51, reading: "めいし", japanese: "名刺", meaning: "Kartu nama" },
  { id: 52, reading: "カード", japanese: "カード", meaning: "Kartu" },
  { id: 53, reading: "えんぴつ", japanese: "鉛筆", meaning: "Pensil" },
  { id: 54, reading: "ボールペン", japanese: "ボールペン", meaning: "Bolpoin" },
  { id: 55, reading: "シャープペンシル", japanese: "シャープペンシル", meaning: "Pensil mekanik" },
  { id: 56, reading: "かぎ", japanese: "鍵", meaning: "Kunci" },
  { id: 57, reading: "とけい", japanese: "時計", meaning: "Jam , arloji" },
  { id: 58, reading: "かさ", japanese: "傘", meaning: "Payung" },
  { id: 59, reading: "かばん", japanese: "鞄", meaning: "Tas" },
  { id: 60, reading: "テレビ", japanese: "テレビ", meaning: "Televisi" },
  { id: 61, reading: "ラジオ", japanese: "ラジオ", meaning: "Radio" },
  { id: 62, reading: "カメラ", japanese: "カメラ", meaning: "Kamera" },
  { id: 63, reading: "コンピューター", japanese: "コンピューター", meaning: "Komputer" },
  { id: 64, reading: "くるま", japanese: "車", meaning: "Mobil" },
  { id: 65, reading: "つくえ", japanese: "机", meaning: "Meja" },
  { id: 66, reading: "いす", japanese: "椅子", meaning: "Kursi" },
  { id: 67, reading: "チョコレート", japanese: "チョコレート", meaning: "Coklat" },
  { id: 68, reading: "コーヒー", japanese: "コーヒー", meaning: "Kopi" },
  { id: 69, reading: "おみやげ", japanese: "お土産", meaning: "Oleh-oleh" },
  { id: 70, reading: "えいご", japanese: "英語", meaning: "Bahasa inggris" },
  { id: 71, reading: "にほんご", japanese: "日本語", meaning: "Bahasa jepang" },
  { id: 72, reading: "～ご", japanese: "～語", meaning: "Bahasa ～" },
  { id: 73, reading: "なん", japanese: "何", meaning: "Apa" },
  { id: 74, reading: "そう", japanese: "そう", meaning: "Begitu" },
  { id: 75, reading: "あのう", japanese: "あのう", meaning: "Eee ...(ungkapan ketika ragu)" },
  { id: 76, reading: "えっ", japanese: "えっ", meaning: "Eh (diucapkan ketika mendengar sesuatu diluar dugaan)" },
  { id: 77, reading: "どうぞ", japanese: "どうぞ", meaning: "Silakan" },
  { id: 78, reading: "どうもありがとうございます", japanese: "どうもありがとうございます", meaning: "Terima kasih" },
  { id: 79, reading: "そうですか", japanese: "そうですか", meaning: "O,begitu, benarkah?" },
  { id: 80, reading: "ちがいます", japanese: "違います", meaning: "Bukan , Tidak , Salah" },
  { id: 81, reading: "あ", japanese: "あ", meaning: "O,eh (dipakai ketika sadar)" },
  { id: 82, reading: "これからおせわになります", japanese: "これからお世話になります", meaning: "Mulai sekarang saya akan meminta bantuannya" },
  { id: 83, reading: "こちらこそよろしくおねがいします", japanese: "こちらこそよろしくおねがいします", meaning: "Ya sama-sama" },
];

const chapter3Words: VocabularyItem[] = [
  { id: 84, reading: 'ここ', japanese: 'ここ', meaning: 'Disini' },
  { id: 85, reading: 'そこ', japanese: 'そこ', meaning: 'Disitu' },
  { id: 86, reading: 'あそこ', japanese: 'あそこ', meaning: 'Disana' },
  { id: 87, reading: 'どこ', japanese: 'どこ', meaning: 'Dimana?' },
  { id: 88, reading: 'こちら', japanese: 'こちら', meaning: 'Disini' },
  { id: 89, reading: 'そちら', japanese: 'そちら', meaning: 'Disitu' },
  { id: 90, reading: 'あちら', japanese: 'あちら', meaning: 'Disana' },
  { id: 91, reading: 'どちら', japanese: 'どちら', meaning: 'Dimana ?' },
  { id: 92, reading: 'きょうしつ', japanese: '教室', meaning: 'Ruang kelas' },
  { id: 93, reading: 'しょくどう', japanese: '食堂', meaning: 'Ruang makan, Kantin' },
  { id: 94, reading: 'じむしょ', japanese: '事務所', meaning: 'Kantor' },
  { id: 95, reading: 'かいぎしつ', japanese: '会議室', meaning: 'Ruang rapat' },
  { id: 96, reading: 'うけつけ', japanese: '受付', meaning: 'Meja informasi' },
  { id: 97, reading: 'ロビー', japanese: 'ロビー', meaning: 'Ruang tunggu, lobi' },
  { id: 98, reading: 'へや', japanese: '部屋', meaning: 'Kamar' },
  { id: 99, reading: 'おてあらい', japanese: 'お手洗い', meaning: 'Kamar kecil, WC' },
  { id: 100, reading: 'トイレ', japanese: 'トイレ', meaning: 'Toilet' },
  { id: 101, reading: 'かいだん', japanese: '階段', meaning: 'Tangga' },
  { id: 102, reading: 'エレベーター', japanese: 'エレベーター', meaning: 'Lift' },
  { id: 103, reading: 'エスカレーター', japanese: 'エスカレーター', meaning: 'Eskalator, tangga berjalan' },
  { id: 104, reading: 'じどうはんばいき', japanese: '自動販売機', meaning: 'Mesin jual otomatis' },
  { id: 105, reading: 'でんわ', japanese: '電話', meaning: 'Telepon' },
  { id: 106, reading: 'おくに', japanese: 'お国', meaning: 'Negara' },
  { id: 107, reading: 'かいしゃ', japanese: '会社', meaning: 'Perusahaan' },
  { id: 108, reading: 'うち', japanese: '家', meaning: 'Rumah' },
  { id: 109, reading: 'くつ', japanese: '靴', meaning: 'Sepatu' },
  { id: 110, reading: 'ネクタイ', japanese: 'ネクタイ', meaning: 'Dasi' },
  { id: 111, reading: 'ワイン', japanese: 'ワイン', meaning: 'Anggur putih' },
  { id: 112, reading: 'うりば', japanese: '売り場', meaning: 'Tempat penjualan' },
  { id: 113, reading: 'ちか', japanese: '地下', meaning: 'Bawah tanah , basement' },
  { id: 114, reading: '～かい', japanese: '～階', meaning: 'lantai～/ tingkat～' },
  { id: 115, reading: 'なんがい', japanese: '何階', meaning: 'Lantai berapa?' },
  { id: 116, reading: '～えん', japanese: '～円', meaning: '～yen' },
  { id: 117, reading: 'いくら', japanese: 'いくら', meaning: 'Berapa?' },
  { id: 118, reading: 'ひゃく', japanese: '百', meaning: 'Seratus' },
  { id: 119, reading: 'せん', japanese: '千', meaning: 'Seribu' },
  { id: 120, reading: 'まん', japanese: '万', meaning: 'Puluh ribu' },
  { id: 121, reading: 'すみません', japanese: 'すみません', meaning: 'Maaf' },
  { id: 122, reading: 'どうも', japanese: 'どうも', meaning: 'Terima kasih' },
  { id: 123, reading: 'いらっしゃいませ', japanese: 'いらっしゃいませ', meaning: 'Selamat datang' },
  { id: 124, reading: 'みせてください', japanese: '見せてください', meaning: 'Tolong perlihatkan' },
  { id: 125, reading: 'じゃ', japanese: 'じゃ', meaning: 'Kalau begitu' },
  { id: 126, reading: '～をください', japanese: '～をください', meaning: 'Tolong ～' },
  { id: 127, reading: 'イタリア', japanese: 'イタリア', meaning: 'Italia' },
  { id: 128, reading: 'スイス', japanese: 'スイス', meaning: 'Swis' },
  { id: 129, reading: 'フランス', japanese: 'フランス', meaning: 'Perancis' },
  { id: 130, reading: 'ジャカルタ', japanese: 'ジャカルタ', meaning: 'Jakarta' },
  { id: 131, reading: 'バンコク', japanese: 'バンコク', meaning: 'Bangkok' },
  { id: 132, reading: 'ベルリン', japanese: 'ベルリン', meaning: 'Berlin' },
  { id: 133, reading: 'おくじょう', japanese: '屋上', meaning: 'Lantai atas' },
  { id: 134, reading: 'レストラン', japanese: 'レストラン', meaning: 'Restoran' },
  { id: 135, reading: 'ゆうえんち', japanese: '遊園地', meaning: 'Tempat hiburan' },
  { id: 136, reading: 'もよおしものかいじょう', japanese: '催し物会場', meaning: 'Tempat pertunjukan' },
  { id: 137, reading: 'めがね', japanese: '眼鏡', meaning: 'Kacamata' },
  { id: 138, reading: 'スポーツようひん', japanese: 'スポーツ用品', meaning: 'Peralatan olahraga' },
  { id: 139, reading: 'りょこうようひん', japanese: '旅行用品', meaning: 'Peralatan wisata' },
  { id: 140, reading: 'こどものふく', japanese: '子供の服', meaning: 'Pakaian anak' },
  { id: 141, reading: 'おもちゃ', japanese: 'おもちゃ', meaning: 'Mainan' },
  { id: 142, reading: 'ぶんぼうぐ', japanese: '文房具', meaning: 'Alat tulis' },
  { id: 143, reading: 'かぐ', japanese: '家具', meaning: 'Perlengkapan rumah' },
  { id: 144, reading: 'しょっき', japanese: '食器', meaning: 'Peralatan makan' },
  { id: 145, reading: 'でんかせいひん', japanese: '電化製品', meaning: 'Barang elektronik' },
  { id: 146, reading: 'しんしふく', japanese: '紳士服', meaning: 'Pakaian pria' },
  { id: 147, reading: 'ふじんふく', japanese: '婦人服', meaning: 'Pakaian wanita' },
  { id: 148, reading: 'アクセサリー', japanese: 'アクセサリー', meaning: 'Perhiasan, aksesoris' },
  { id: 149, reading: 'けしょうひん', japanese: '化粧品', meaning: 'Kosmetik' },
  { id: 150, reading: 'しょくひん', japanese: '食品', meaning: 'Makanan' },
];

const allWords: VocabularyItem[] = [...chapter1Words, ...chapter2Words, ...chapter3Words];

export const chapters: Chapter[] = Array.from({ length: 50 }, (_, i) => {
  const chapterNumber = i + 1;
  let words: VocabularyItem[] = [];
  if (chapterNumber === 1) words = chapter1Words;
  if (chapterNumber === 2) words = chapter2Words;
  if (chapterNumber === 3) words = chapter3Words;

  return {
    chapter: chapterNumber,
    words: words,
  };
});

// For practice page, we can provide a flat list for simplicity of random selection
export const vocabularyList: VocabularyItem[] = allWords;
